# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_monitor_response_dto import CreateMonitorResponseDto
from ..types.delete_monitor_response_dto import DeleteMonitorResponseDto
from ..types.list_monitors_response_dto import ListMonitorsResponseDto
from ..types.monitor_status_history_response_dto import MonitorStatusHistoryResponseDto
from ..types.ownership_filter import OwnershipFilter
from ..types.pull_monitor_response_dto import PullMonitorResponseDto
from ..types.update_monitor_response_dto import UpdateMonitorResponseDto
from .raw_client import AsyncRawMonitorsClient, RawMonitorsClient
from .types.disable_monitor_response import DisableMonitorResponse
from .types.enable_monitor_response import EnableMonitorResponse
from .types.list_monitor_jobs_request_sort import ListMonitorJobsRequestSort
from .types.list_monitor_jobs_response import ListMonitorJobsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MonitorsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMonitorsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMonitorsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMonitorsClient
        """
        return self._raw_client

    def list_monitors(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        ownership: typing.Optional[OwnershipFilter] = None,
        project_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMonitorsResponseDto:
        """
        Returns all monitors created by the authenticated user.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of records per page.

        search : typing.Optional[str]
            Filter results by text (case-insensitive substring match).

        ownership : typing.Optional[OwnershipFilter]

        project_id : typing.Optional[str]
            Filter results to resources belonging to this project.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMonitorsResponseDto
            List of user monitors

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.monitors.list_monitors(
            project_id="60a85db4-78ec-4b78-876a-bc7d9cdadd04",
        )
        """
        _response = self._raw_client.list_monitors(
            page=page,
            page_size=page_size,
            search=search,
            ownership=ownership,
            project_id=project_id,
            request_options=request_options,
        )
        return _response.data

    def create_monitor(
        self,
        *,
        reference_job_id: str,
        schedule: str,
        timezone: typing.Optional[str] = OMIT,
        webhook_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        backfill: typing.Optional[bool] = OMIT,
        project_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMonitorResponseDto:
        """
        Create a scheduled monitor based on a reference job.

        Parameters
        ----------
        reference_job_id : str
            Job ID to use as template for scheduled runs. Defines the query, validators, and enrichments used for each scheduled run.

            If [`backfill`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/monitors/create-monitor#body-backfill) is true, the job's `end_date` must be within the last 7 days.

        schedule : str
            Monitor schedule in plain text format. Minimum frequency depends on your plan.

        timezone : typing.Optional[str]
            The IANA timezone identifier used as the fallback when the `schedule` string does not include an explicit timezone.

            If the schedule includes a timezone abbreviation (for example, `"every day at 9am EST"`), the parsed timezone takes priority and this value is ignored.

        webhook_ids : typing.Optional[typing.Sequence[str]]
            IDs of centralized webhooks to notify on each run completion.
            Passing IDs here is equivalent to calling
            `POST /catchAll/webhooks/{webhook_id}/resources` for each ID after creation.
            Maximum 5 per monitor.

        limit : typing.Optional[int]
            Maximum number of records per monitor run. If not provided, defaults to the plan limit.

        backfill : typing.Optional[bool]
            If true, fills the data gap between the reference job's `end_date` and the first scheduled run. The reference job's `end_date` must be within the last 7 days.

            If false, no gap filling occurs and the first run uses the current cron window only — the reference job's age does not matter.

        project_id : typing.Optional[str]
            Project to assign this monitor to. The monitor appears in the project's resource list after creation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMonitorResponseDto
            Monitor created successfully

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.monitors.create_monitor(
            reference_job_id="5f0c9087-85cb-4917-b3c7-e5a5eff73a0c",
            schedule="every day at 12 PM",
            timezone="UTC",
            webhook_ids=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"],
            limit=10,
            backfill=True,
        )
        """
        _response = self._raw_client.create_monitor(
            reference_job_id=reference_job_id,
            schedule=schedule,
            timezone=timezone,
            webhook_ids=webhook_ids,
            limit=limit,
            backfill=backfill,
            project_id=project_id,
            request_options=request_options,
        )
        return _response.data

    def pull_monitor_results(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PullMonitorResponseDto:
        """
        Retrieve aggregated results from all jobs executed by a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PullMonitorResponseDto
            Monitor results retrieved successfully

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.monitors.pull_monitor_results(
            monitor_id="monitor_id",
        )
        """
        _response = self._raw_client.pull_monitor_results(monitor_id, request_options=request_options)
        return _response.data

    def list_monitor_jobs(
        self,
        monitor_id: str,
        *,
        sort: typing.Optional[ListMonitorJobsRequestSort] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMonitorJobsResponse:
        """
        Return all jobs executed by a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        sort : typing.Optional[ListMonitorJobsRequestSort]
            Sort by start_date (asc or desc).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMonitorJobsResponse
            List of monitor jobs

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.monitors.list_monitor_jobs(
            monitor_id="monitor_id",
        )
        """
        _response = self._raw_client.list_monitor_jobs(monitor_id, sort=sort, request_options=request_options)
        return _response.data

    def get_monitor_status_history(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MonitorStatusHistoryResponseDto:
        """
        Returns the full execution history of a monitor as a list of status entries, ordered from newest to oldest.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorStatusHistoryResponseDto
            Monitor status history retrieved successfully.

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.monitors.get_monitor_status_history(
            monitor_id="monitor_id",
        )
        """
        _response = self._raw_client.get_monitor_status_history(monitor_id, request_options=request_options)
        return _response.data

    def enable_monitor(
        self,
        monitor_id: str,
        *,
        backfill: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EnableMonitorResponse:
        """
        Resume scheduled job execution for a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        backfill : typing.Optional[bool]
            If true, fills the data gap between the last job's `end_date` and the first scheduled run after enabling. The last job's `end_date` must be within the last 7 days.

            If false, no gap filling occurs and the first run uses the current cron window only — the last job's age does not matter.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnableMonitorResponse
            Monitor enabled successfully

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.monitors.enable_monitor(
            monitor_id="monitor_id",
            backfill=True,
        )
        """
        _response = self._raw_client.enable_monitor(monitor_id, backfill=backfill, request_options=request_options)
        return _response.data

    def disable_monitor(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DisableMonitorResponse:
        """
        Stop scheduled job execution for a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DisableMonitorResponse
            Monitor disabled successfully

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.monitors.disable_monitor(
            monitor_id="monitor_id",
        )
        """
        _response = self._raw_client.disable_monitor(monitor_id, request_options=request_options)
        return _response.data

    def delete_monitor(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteMonitorResponseDto:
        """
        Soft-deletes a monitor. The monitor is flagged as deleted, stops
        executing scheduled jobs immediately, and no longer appears in list
        results.

        Only the monitor owner can delete a monitor. Returns `404` if the
        monitor is not found or does not belong to the authenticated user.

        Deleting an already-deleted monitor returns `200`.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteMonitorResponseDto
            Monitor deleted successfully (or already deleted).

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.monitors.delete_monitor(
            monitor_id="monitor_id",
        )
        """
        _response = self._raw_client.delete_monitor(monitor_id, request_options=request_options)
        return _response.data

    def update_monitor(
        self,
        monitor_id: str,
        *,
        webhook_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateMonitorResponseDto:
        """
        Update the webhook configuration for an existing monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        webhook_ids : typing.Optional[typing.Sequence[str]]
            Updated list of centralized webhook IDs for this monitor.

            Replaces all existing webhook assignments. Pass an empty array `[]` to clear all assignments. Omit to leave existing assignments unchanged.

        limit : typing.Optional[int]
            Updated maximum number of records per monitor run.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateMonitorResponseDto
            Monitor updated successfully

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.monitors.update_monitor(
            monitor_id="monitor_id",
            webhook_ids=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"],
        )
        """
        _response = self._raw_client.update_monitor(
            monitor_id, webhook_ids=webhook_ids, limit=limit, request_options=request_options
        )
        return _response.data


class AsyncMonitorsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMonitorsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMonitorsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMonitorsClient
        """
        return self._raw_client

    async def list_monitors(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        ownership: typing.Optional[OwnershipFilter] = None,
        project_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMonitorsResponseDto:
        """
        Returns all monitors created by the authenticated user.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of records per page.

        search : typing.Optional[str]
            Filter results by text (case-insensitive substring match).

        ownership : typing.Optional[OwnershipFilter]

        project_id : typing.Optional[str]
            Filter results to resources belonging to this project.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMonitorsResponseDto
            List of user monitors

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.list_monitors(
                project_id="60a85db4-78ec-4b78-876a-bc7d9cdadd04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_monitors(
            page=page,
            page_size=page_size,
            search=search,
            ownership=ownership,
            project_id=project_id,
            request_options=request_options,
        )
        return _response.data

    async def create_monitor(
        self,
        *,
        reference_job_id: str,
        schedule: str,
        timezone: typing.Optional[str] = OMIT,
        webhook_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        backfill: typing.Optional[bool] = OMIT,
        project_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMonitorResponseDto:
        """
        Create a scheduled monitor based on a reference job.

        Parameters
        ----------
        reference_job_id : str
            Job ID to use as template for scheduled runs. Defines the query, validators, and enrichments used for each scheduled run.

            If [`backfill`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/monitors/create-monitor#body-backfill) is true, the job's `end_date` must be within the last 7 days.

        schedule : str
            Monitor schedule in plain text format. Minimum frequency depends on your plan.

        timezone : typing.Optional[str]
            The IANA timezone identifier used as the fallback when the `schedule` string does not include an explicit timezone.

            If the schedule includes a timezone abbreviation (for example, `"every day at 9am EST"`), the parsed timezone takes priority and this value is ignored.

        webhook_ids : typing.Optional[typing.Sequence[str]]
            IDs of centralized webhooks to notify on each run completion.
            Passing IDs here is equivalent to calling
            `POST /catchAll/webhooks/{webhook_id}/resources` for each ID after creation.
            Maximum 5 per monitor.

        limit : typing.Optional[int]
            Maximum number of records per monitor run. If not provided, defaults to the plan limit.

        backfill : typing.Optional[bool]
            If true, fills the data gap between the reference job's `end_date` and the first scheduled run. The reference job's `end_date` must be within the last 7 days.

            If false, no gap filling occurs and the first run uses the current cron window only — the reference job's age does not matter.

        project_id : typing.Optional[str]
            Project to assign this monitor to. The monitor appears in the project's resource list after creation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMonitorResponseDto
            Monitor created successfully

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.create_monitor(
                reference_job_id="5f0c9087-85cb-4917-b3c7-e5a5eff73a0c",
                schedule="every day at 12 PM",
                timezone="UTC",
                webhook_ids=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"],
                limit=10,
                backfill=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_monitor(
            reference_job_id=reference_job_id,
            schedule=schedule,
            timezone=timezone,
            webhook_ids=webhook_ids,
            limit=limit,
            backfill=backfill,
            project_id=project_id,
            request_options=request_options,
        )
        return _response.data

    async def pull_monitor_results(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PullMonitorResponseDto:
        """
        Retrieve aggregated results from all jobs executed by a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PullMonitorResponseDto
            Monitor results retrieved successfully

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.pull_monitor_results(
                monitor_id="monitor_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.pull_monitor_results(monitor_id, request_options=request_options)
        return _response.data

    async def list_monitor_jobs(
        self,
        monitor_id: str,
        *,
        sort: typing.Optional[ListMonitorJobsRequestSort] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMonitorJobsResponse:
        """
        Return all jobs executed by a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        sort : typing.Optional[ListMonitorJobsRequestSort]
            Sort by start_date (asc or desc).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMonitorJobsResponse
            List of monitor jobs

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.list_monitor_jobs(
                monitor_id="monitor_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_monitor_jobs(monitor_id, sort=sort, request_options=request_options)
        return _response.data

    async def get_monitor_status_history(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MonitorStatusHistoryResponseDto:
        """
        Returns the full execution history of a monitor as a list of status entries, ordered from newest to oldest.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorStatusHistoryResponseDto
            Monitor status history retrieved successfully.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.get_monitor_status_history(
                monitor_id="monitor_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_monitor_status_history(monitor_id, request_options=request_options)
        return _response.data

    async def enable_monitor(
        self,
        monitor_id: str,
        *,
        backfill: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EnableMonitorResponse:
        """
        Resume scheduled job execution for a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        backfill : typing.Optional[bool]
            If true, fills the data gap between the last job's `end_date` and the first scheduled run after enabling. The last job's `end_date` must be within the last 7 days.

            If false, no gap filling occurs and the first run uses the current cron window only — the last job's age does not matter.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnableMonitorResponse
            Monitor enabled successfully

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.enable_monitor(
                monitor_id="monitor_id",
                backfill=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.enable_monitor(
            monitor_id, backfill=backfill, request_options=request_options
        )
        return _response.data

    async def disable_monitor(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DisableMonitorResponse:
        """
        Stop scheduled job execution for a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DisableMonitorResponse
            Monitor disabled successfully

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.disable_monitor(
                monitor_id="monitor_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.disable_monitor(monitor_id, request_options=request_options)
        return _response.data

    async def delete_monitor(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteMonitorResponseDto:
        """
        Soft-deletes a monitor. The monitor is flagged as deleted, stops
        executing scheduled jobs immediately, and no longer appears in list
        results.

        Only the monitor owner can delete a monitor. Returns `404` if the
        monitor is not found or does not belong to the authenticated user.

        Deleting an already-deleted monitor returns `200`.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteMonitorResponseDto
            Monitor deleted successfully (or already deleted).

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.delete_monitor(
                monitor_id="monitor_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_monitor(monitor_id, request_options=request_options)
        return _response.data

    async def update_monitor(
        self,
        monitor_id: str,
        *,
        webhook_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateMonitorResponseDto:
        """
        Update the webhook configuration for an existing monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        webhook_ids : typing.Optional[typing.Sequence[str]]
            Updated list of centralized webhook IDs for this monitor.

            Replaces all existing webhook assignments. Pass an empty array `[]` to clear all assignments. Omit to leave existing assignments unchanged.

        limit : typing.Optional[int]
            Updated maximum number of records per monitor run.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateMonitorResponseDto
            Monitor updated successfully

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.update_monitor(
                monitor_id="monitor_id",
                webhook_ids=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_monitor(
            monitor_id, webhook_ids=webhook_ids, limit=limit, request_options=request_options
        )
        return _response.data
