# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.create_monitor_response_dto import CreateMonitorResponseDto
from ..types.delete_monitor_response_dto import DeleteMonitorResponseDto
from ..types.error import Error
from ..types.list_monitors_response_dto import ListMonitorsResponseDto
from ..types.monitor_status_history_response_dto import MonitorStatusHistoryResponseDto
from ..types.ownership_filter import OwnershipFilter
from ..types.pull_monitor_response_dto import PullMonitorResponseDto
from ..types.update_monitor_response_dto import UpdateMonitorResponseDto
from ..types.validation_error_response import ValidationErrorResponse
from ..types.webhook_dto import WebhookDto
from .types.disable_monitor_response import DisableMonitorResponse
from .types.enable_monitor_response import EnableMonitorResponse
from .types.list_monitor_jobs_request_sort import ListMonitorJobsRequestSort
from .types.list_monitor_jobs_response import ListMonitorJobsResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawMonitorsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_monitors(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        ownership: typing.Optional[OwnershipFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListMonitorsResponseDto]:
        """
        Returns all monitors created by the authenticated user.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of records per page.

        search : typing.Optional[str]
            Filter results by text (case-insensitive substring match).

        ownership : typing.Optional[OwnershipFilter]
            Filter results by ownership. Defaults to `all`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListMonitorsResponseDto]
            List of user monitors
        """
        _response = self._client_wrapper.httpx_client.request(
            "catchAll/monitors",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "search": search,
                "ownership": ownership,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMonitorsResponseDto,
                    parse_obj_as(
                        type_=ListMonitorsResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_monitor(
        self,
        *,
        reference_job_id: str,
        schedule: str,
        webhook: typing.Optional[WebhookDto] = OMIT,
        limit: typing.Optional[int] = OMIT,
        backfill: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateMonitorResponseDto]:
        """
        Create a scheduled monitor based on a reference job.

        Parameters
        ----------
        reference_job_id : str
            Job ID to use as template for scheduled runs. Defines the query, validators, and enrichments used for each scheduled run.

            If [`backfill`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/monitors/create-monitor#body-backfill) is true, the job's `end_date` must be within the last 7 days.

        schedule : str
            Monitor schedule in plain text format (e.g. 'every day at 12 PM UTC', 'every 48 hours').

            Minimum frequency depends on your plan.

        webhook : typing.Optional[WebhookDto]
            Optional webhook to receive notifications when jobs complete.

        limit : typing.Optional[int]
            Maximum number of records per monitor run. If not provided, defaults to the plan limit.

        backfill : typing.Optional[bool]
            If true, fills the data gap between the reference job's `end_date` and the first scheduled run. The reference job's `end_date` must be within the last 7 days.

            If false, no gap filling occurs and the first run uses the current cron window only — the reference job's age does not matter.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateMonitorResponseDto]
            Monitor created successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "catchAll/monitors/create",
            method="POST",
            json={
                "reference_job_id": reference_job_id,
                "schedule": schedule,
                "webhook": convert_and_respect_annotation_metadata(
                    object_=webhook, annotation=WebhookDto, direction="write"
                ),
                "limit": limit,
                "backfill": backfill,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateMonitorResponseDto,
                    parse_obj_as(
                        type_=CreateMonitorResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def pull_monitor_results(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PullMonitorResponseDto]:
        """
        Retrieve aggregated results from all jobs executed by a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PullMonitorResponseDto]
            Monitor results retrieved successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/pull/{encode_path_param(monitor_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PullMonitorResponseDto,
                    parse_obj_as(
                        type_=PullMonitorResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_monitor_jobs(
        self,
        monitor_id: str,
        *,
        sort: typing.Optional[ListMonitorJobsRequestSort] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListMonitorJobsResponse]:
        """
        Return all jobs executed by a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        sort : typing.Optional[ListMonitorJobsRequestSort]
            Sort by start_date (asc or desc).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListMonitorJobsResponse]
            List of monitor jobs
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/{encode_path_param(monitor_id)}/jobs",
            method="GET",
            params={
                "sort": sort,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMonitorJobsResponse,
                    parse_obj_as(
                        type_=ListMonitorJobsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_monitor_status_history(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MonitorStatusHistoryResponseDto]:
        """
        Returns the full execution history of a monitor as a list of status entries, ordered from newest to oldest.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MonitorStatusHistoryResponseDto]
            Monitor status history retrieved successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/{encode_path_param(monitor_id)}/status",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MonitorStatusHistoryResponseDto,
                    parse_obj_as(
                        type_=MonitorStatusHistoryResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def enable_monitor(
        self,
        monitor_id: str,
        *,
        backfill: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[EnableMonitorResponse]:
        """
        Resume scheduled job execution for a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        backfill : typing.Optional[bool]
            If true, fills the data gap between the last job's `end_date` and the first scheduled run after enabling. The last job's `end_date` must be within the last 7 days.

            If false, no gap filling occurs and the first run uses the current cron window only — the last job's age does not matter.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EnableMonitorResponse]
            Monitor enabled successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/{encode_path_param(monitor_id)}/enable",
            method="POST",
            json={
                "backfill": backfill,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EnableMonitorResponse,
                    parse_obj_as(
                        type_=EnableMonitorResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def disable_monitor(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DisableMonitorResponse]:
        """
        Stop scheduled job execution for a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DisableMonitorResponse]
            Monitor disabled successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/{encode_path_param(monitor_id)}/disable",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DisableMonitorResponse,
                    parse_obj_as(
                        type_=DisableMonitorResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_monitor(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DeleteMonitorResponseDto]:
        """
        Soft-deletes a monitor. The monitor is flagged as deleted, stops
        executing scheduled jobs immediately, and no longer appears in list
        results.

        Only the monitor owner can delete a monitor. Returns `404` if the
        monitor is not found or does not belong to the authenticated user.

        Deleting an already-deleted monitor returns `200`.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeleteMonitorResponseDto]
            Monitor deleted successfully (or already deleted).
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/{encode_path_param(monitor_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeleteMonitorResponseDto,
                    parse_obj_as(
                        type_=DeleteMonitorResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_monitor(
        self,
        monitor_id: str,
        *,
        webhook: typing.Optional[WebhookDto] = OMIT,
        limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UpdateMonitorResponseDto]:
        """
        Update the webhook configuration for an existing monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        webhook : typing.Optional[WebhookDto]
            Updated webhook configuration.

        limit : typing.Optional[int]
            Updated maximum number of records per monitor run.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UpdateMonitorResponseDto]
            Monitor updated successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/{encode_path_param(monitor_id)}",
            method="PATCH",
            json={
                "webhook": convert_and_respect_annotation_metadata(
                    object_=webhook, annotation=WebhookDto, direction="write"
                ),
                "limit": limit,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateMonitorResponseDto,
                    parse_obj_as(
                        type_=UpdateMonitorResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawMonitorsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_monitors(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        ownership: typing.Optional[OwnershipFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListMonitorsResponseDto]:
        """
        Returns all monitors created by the authenticated user.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of records per page.

        search : typing.Optional[str]
            Filter results by text (case-insensitive substring match).

        ownership : typing.Optional[OwnershipFilter]
            Filter results by ownership. Defaults to `all`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListMonitorsResponseDto]
            List of user monitors
        """
        _response = await self._client_wrapper.httpx_client.request(
            "catchAll/monitors",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "search": search,
                "ownership": ownership,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMonitorsResponseDto,
                    parse_obj_as(
                        type_=ListMonitorsResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_monitor(
        self,
        *,
        reference_job_id: str,
        schedule: str,
        webhook: typing.Optional[WebhookDto] = OMIT,
        limit: typing.Optional[int] = OMIT,
        backfill: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateMonitorResponseDto]:
        """
        Create a scheduled monitor based on a reference job.

        Parameters
        ----------
        reference_job_id : str
            Job ID to use as template for scheduled runs. Defines the query, validators, and enrichments used for each scheduled run.

            If [`backfill`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/monitors/create-monitor#body-backfill) is true, the job's `end_date` must be within the last 7 days.

        schedule : str
            Monitor schedule in plain text format (e.g. 'every day at 12 PM UTC', 'every 48 hours').

            Minimum frequency depends on your plan.

        webhook : typing.Optional[WebhookDto]
            Optional webhook to receive notifications when jobs complete.

        limit : typing.Optional[int]
            Maximum number of records per monitor run. If not provided, defaults to the plan limit.

        backfill : typing.Optional[bool]
            If true, fills the data gap between the reference job's `end_date` and the first scheduled run. The reference job's `end_date` must be within the last 7 days.

            If false, no gap filling occurs and the first run uses the current cron window only — the reference job's age does not matter.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateMonitorResponseDto]
            Monitor created successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "catchAll/monitors/create",
            method="POST",
            json={
                "reference_job_id": reference_job_id,
                "schedule": schedule,
                "webhook": convert_and_respect_annotation_metadata(
                    object_=webhook, annotation=WebhookDto, direction="write"
                ),
                "limit": limit,
                "backfill": backfill,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateMonitorResponseDto,
                    parse_obj_as(
                        type_=CreateMonitorResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def pull_monitor_results(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PullMonitorResponseDto]:
        """
        Retrieve aggregated results from all jobs executed by a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PullMonitorResponseDto]
            Monitor results retrieved successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/pull/{encode_path_param(monitor_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PullMonitorResponseDto,
                    parse_obj_as(
                        type_=PullMonitorResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_monitor_jobs(
        self,
        monitor_id: str,
        *,
        sort: typing.Optional[ListMonitorJobsRequestSort] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListMonitorJobsResponse]:
        """
        Return all jobs executed by a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        sort : typing.Optional[ListMonitorJobsRequestSort]
            Sort by start_date (asc or desc).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListMonitorJobsResponse]
            List of monitor jobs
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/{encode_path_param(monitor_id)}/jobs",
            method="GET",
            params={
                "sort": sort,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMonitorJobsResponse,
                    parse_obj_as(
                        type_=ListMonitorJobsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_monitor_status_history(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MonitorStatusHistoryResponseDto]:
        """
        Returns the full execution history of a monitor as a list of status entries, ordered from newest to oldest.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MonitorStatusHistoryResponseDto]
            Monitor status history retrieved successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/{encode_path_param(monitor_id)}/status",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MonitorStatusHistoryResponseDto,
                    parse_obj_as(
                        type_=MonitorStatusHistoryResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def enable_monitor(
        self,
        monitor_id: str,
        *,
        backfill: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[EnableMonitorResponse]:
        """
        Resume scheduled job execution for a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        backfill : typing.Optional[bool]
            If true, fills the data gap between the last job's `end_date` and the first scheduled run after enabling. The last job's `end_date` must be within the last 7 days.

            If false, no gap filling occurs and the first run uses the current cron window only — the last job's age does not matter.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EnableMonitorResponse]
            Monitor enabled successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/{encode_path_param(monitor_id)}/enable",
            method="POST",
            json={
                "backfill": backfill,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EnableMonitorResponse,
                    parse_obj_as(
                        type_=EnableMonitorResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def disable_monitor(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DisableMonitorResponse]:
        """
        Stop scheduled job execution for a monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DisableMonitorResponse]
            Monitor disabled successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/{encode_path_param(monitor_id)}/disable",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DisableMonitorResponse,
                    parse_obj_as(
                        type_=DisableMonitorResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_monitor(
        self, monitor_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DeleteMonitorResponseDto]:
        """
        Soft-deletes a monitor. The monitor is flagged as deleted, stops
        executing scheduled jobs immediately, and no longer appears in list
        results.

        Only the monitor owner can delete a monitor. Returns `404` if the
        monitor is not found or does not belong to the authenticated user.

        Deleting an already-deleted monitor returns `200`.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeleteMonitorResponseDto]
            Monitor deleted successfully (or already deleted).
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/{encode_path_param(monitor_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeleteMonitorResponseDto,
                    parse_obj_as(
                        type_=DeleteMonitorResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_monitor(
        self,
        monitor_id: str,
        *,
        webhook: typing.Optional[WebhookDto] = OMIT,
        limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UpdateMonitorResponseDto]:
        """
        Update the webhook configuration for an existing monitor.

        Parameters
        ----------
        monitor_id : str
            Monitor identifier.

        webhook : typing.Optional[WebhookDto]
            Updated webhook configuration.

        limit : typing.Optional[int]
            Updated maximum number of records per monitor run.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UpdateMonitorResponseDto]
            Monitor updated successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/monitors/{encode_path_param(monitor_id)}",
            method="PATCH",
            json={
                "webhook": convert_and_respect_annotation_metadata(
                    object_=webhook, annotation=WebhookDto, direction="write"
                ),
                "limit": limit,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateMonitorResponseDto,
                    parse_obj_as(
                        type_=UpdateMonitorResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
