# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        BaseRecord,
        BaseRecordEnrichment,
        BaseRecordEnrichmentEnrichmentConfidence,
        Citation,
        CompanyEnrichmentOutput,
        CompanyEnrichmentOutputMetadata,
        CompanyEnrichmentOutputMetadataDomainUrlConfidence,
        Context,
        ContinueResponseDto,
        CreateMonitorResponseDto,
        EndDate,
        EnrichmentSchema,
        EnrichmentType,
        Error,
        InitializeResponseDto,
        JobStep,
        Limit,
        ListMonitorsResponseDto,
        ListUserJobsResponseDto,
        MonitorCitation,
        MonitorJobItem,
        MonitorListItemDto,
        MonitorRecord,
        PublicJobStatus,
        PullJobResponseDto,
        PullJobResponseDtoDateRange,
        PullMonitorResponseDto,
        PullMonitorResponseDtoRunInfo,
        Query,
        Record,
        ReferenceJob,
        StartDate,
        StatusResponseDto,
        SubmitResponseDto,
        UpdateMonitorResponseDto,
        UserJob,
        ValidationErrorDetail,
        ValidationErrorDetailLocItem,
        ValidationErrorResponse,
        ValidatorSchema,
        WebhookDto,
        WebhookDtoMethod,
        WebhookPayload,
    )
    from .errors import BadRequestError, ForbiddenError, NotFoundError, UnprocessableEntityError
    from . import jobs, meta, monitors
    from .client import AsyncCatchAllApi, CatchAllApi
    from .environment import CatchAllApiEnvironment
    from .meta import GetVersionResponse, HealthCheckResponse
    from .monitors import (
        DisableMonitorResponse,
        EnableMonitorResponse,
        ListMonitorJobsRequestSort,
        ListMonitorJobsResponse,
        ListMonitorJobsResponseSortOrder,
    )
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncCatchAllApi": ".client",
    "BadRequestError": ".errors",
    "BaseRecord": ".types",
    "BaseRecordEnrichment": ".types",
    "BaseRecordEnrichmentEnrichmentConfidence": ".types",
    "CatchAllApi": ".client",
    "CatchAllApiEnvironment": ".environment",
    "Citation": ".types",
    "CompanyEnrichmentOutput": ".types",
    "CompanyEnrichmentOutputMetadata": ".types",
    "CompanyEnrichmentOutputMetadataDomainUrlConfidence": ".types",
    "Context": ".types",
    "ContinueResponseDto": ".types",
    "CreateMonitorResponseDto": ".types",
    "DisableMonitorResponse": ".monitors",
    "EnableMonitorResponse": ".monitors",
    "EndDate": ".types",
    "EnrichmentSchema": ".types",
    "EnrichmentType": ".types",
    "Error": ".types",
    "ForbiddenError": ".errors",
    "GetVersionResponse": ".meta",
    "HealthCheckResponse": ".meta",
    "InitializeResponseDto": ".types",
    "JobStep": ".types",
    "Limit": ".types",
    "ListMonitorJobsRequestSort": ".monitors",
    "ListMonitorJobsResponse": ".monitors",
    "ListMonitorJobsResponseSortOrder": ".monitors",
    "ListMonitorsResponseDto": ".types",
    "ListUserJobsResponseDto": ".types",
    "MonitorCitation": ".types",
    "MonitorJobItem": ".types",
    "MonitorListItemDto": ".types",
    "MonitorRecord": ".types",
    "NotFoundError": ".errors",
    "PublicJobStatus": ".types",
    "PullJobResponseDto": ".types",
    "PullJobResponseDtoDateRange": ".types",
    "PullMonitorResponseDto": ".types",
    "PullMonitorResponseDtoRunInfo": ".types",
    "Query": ".types",
    "Record": ".types",
    "ReferenceJob": ".types",
    "StartDate": ".types",
    "StatusResponseDto": ".types",
    "SubmitResponseDto": ".types",
    "UnprocessableEntityError": ".errors",
    "UpdateMonitorResponseDto": ".types",
    "UserJob": ".types",
    "ValidationErrorDetail": ".types",
    "ValidationErrorDetailLocItem": ".types",
    "ValidationErrorResponse": ".types",
    "ValidatorSchema": ".types",
    "WebhookDto": ".types",
    "WebhookDtoMethod": ".types",
    "WebhookPayload": ".types",
    "__version__": ".version",
    "jobs": ".jobs",
    "meta": ".meta",
    "monitors": ".monitors",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncCatchAllApi",
    "BadRequestError",
    "BaseRecord",
    "BaseRecordEnrichment",
    "BaseRecordEnrichmentEnrichmentConfidence",
    "CatchAllApi",
    "CatchAllApiEnvironment",
    "Citation",
    "CompanyEnrichmentOutput",
    "CompanyEnrichmentOutputMetadata",
    "CompanyEnrichmentOutputMetadataDomainUrlConfidence",
    "Context",
    "ContinueResponseDto",
    "CreateMonitorResponseDto",
    "DisableMonitorResponse",
    "EnableMonitorResponse",
    "EndDate",
    "EnrichmentSchema",
    "EnrichmentType",
    "Error",
    "ForbiddenError",
    "GetVersionResponse",
    "HealthCheckResponse",
    "InitializeResponseDto",
    "JobStep",
    "Limit",
    "ListMonitorJobsRequestSort",
    "ListMonitorJobsResponse",
    "ListMonitorJobsResponseSortOrder",
    "ListMonitorsResponseDto",
    "ListUserJobsResponseDto",
    "MonitorCitation",
    "MonitorJobItem",
    "MonitorListItemDto",
    "MonitorRecord",
    "NotFoundError",
    "PublicJobStatus",
    "PullJobResponseDto",
    "PullJobResponseDtoDateRange",
    "PullMonitorResponseDto",
    "PullMonitorResponseDtoRunInfo",
    "Query",
    "Record",
    "ReferenceJob",
    "StartDate",
    "StatusResponseDto",
    "SubmitResponseDto",
    "UnprocessableEntityError",
    "UpdateMonitorResponseDto",
    "UserJob",
    "ValidationErrorDetail",
    "ValidationErrorDetailLocItem",
    "ValidationErrorResponse",
    "ValidatorSchema",
    "WebhookDto",
    "WebhookDtoMethod",
    "WebhookPayload",
    "__version__",
    "jobs",
    "meta",
    "monitors",
]
