# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.additional_attributes import AdditionalAttributes
from ..types.create_entities_batch_response import CreateEntitiesBatchResponse
from ..types.create_entity_request import CreateEntityRequest
from ..types.create_entity_response import CreateEntityResponse
from ..types.entity_list_response import EntityListResponse
from ..types.entity_response import EntityResponse
from ..types.entity_sort_by import EntitySortBy
from ..types.entity_status import EntityStatus
from ..types.entity_type import EntityType
from ..types.sort_order import SortOrder
from .raw_client import AsyncRawEntitiesClient, RawEntitiesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EntitiesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEntitiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEntitiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEntitiesClient
        """
        return self._raw_client

    def list_entities(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[EntityStatus] = None,
        entity_type: typing.Optional[EntityType] = None,
        sort_by: typing.Optional[EntitySortBy] = None,
        sort_order: typing.Optional[SortOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityListResponse:
        """
        Returns a paginated list of entities belonging to the authenticated
        organization. Supports filtering by status and entity type, and
        sorting by name, status, or creation date.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of entities per page.

        search : typing.Optional[str]
            Filter entities by name (case-insensitive substring match).

        status : typing.Optional[EntityStatus]

        entity_type : typing.Optional[EntityType]

        sort_by : typing.Optional[EntitySortBy]

        sort_order : typing.Optional[SortOrder]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityListResponse
            Paginated list of entities.

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.entities.list_entities(
            search="NewsCatcher",
        )
        """
        _response = self._raw_client.list_entities(
            page=page,
            page_size=page_size,
            search=search,
            status=status,
            entity_type=entity_type,
            sort_by=sort_by,
            sort_order=sort_order,
            request_options=request_options,
        )
        return _response.data

    def create_entity(
        self,
        *,
        name: str,
        entity_type: typing.Optional[EntityType] = OMIT,
        description: typing.Optional[str] = OMIT,
        additional_attributes: typing.Optional[AdditionalAttributes] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateEntityResponse:
        """
        Creates a new company entity and begins background enrichment.

        The entity status starts as `pending` and transitions to `ready` once
        enrichment completes. Provide as much identifying information as
        possible — `domain` is the highest-signal field because it is
        unambiguous.

        Parameters
        ----------
        name : str
            The company or person name. Required and must be non-empty.

        entity_type : typing.Optional[EntityType]

        description : typing.Optional[str]
            Free-text description of the entity used for disambiguation when similar names exist.

        additional_attributes : typing.Optional[AdditionalAttributes]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateEntityResponse
            Entity created successfully.

        Examples
        --------
        from newscatcher_catchall import (
            AdditionalAttributes,
            CatchAllApi,
            CompanyAttributes,
        )

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.entities.create_entity(
            name="NewsCatcher",
            entity_type="company",
            description="AI-powered news data provider",
            additional_attributes=AdditionalAttributes(
                company_attributes=CompanyAttributes(
                    domain="newscatcherapi.com",
                    key_persons=["Artem Bugara", "Maksym Sugonyaka"],
                    alternative_names=["NC", "NewsCatcher API"],
                ),
            ),
        )
        """
        _response = self._raw_client.create_entity(
            name=name,
            entity_type=entity_type,
            description=description,
            additional_attributes=additional_attributes,
            request_options=request_options,
        )
        return _response.data

    def create_entities_batch(
        self, *, entities: typing.Sequence[CreateEntityRequest], request_options: typing.Optional[RequestOptions] = None
    ) -> CreateEntitiesBatchResponse:
        """
        Creates multiple entities in a single request. Each entity is
        processed independently — a failure in one does not affect others.

        Returns an array of `{id, status}` objects in the same order as
        the input array.

        Parameters
        ----------
        entities : typing.Sequence[CreateEntityRequest]
            Array of entities to create. Each item follows the same schema
            as single entity creation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateEntitiesBatchResponse
            Batch of entities created successfully.

        Examples
        --------
        from newscatcher_catchall import (
            AdditionalAttributes,
            CatchAllApi,
            CompanyAttributes,
            CreateEntityRequest,
        )

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.entities.create_entities_batch(
            entities=[
                CreateEntityRequest(
                    name="OpenAI",
                    entity_type="company",
                    description="Artificial intelligence research company",
                    additional_attributes=AdditionalAttributes(
                        company_attributes=CompanyAttributes(
                            domain="openai.com",
                            key_persons=["Sam Altman"],
                            alternative_names=["Open AI"],
                        ),
                    ),
                ),
                CreateEntityRequest(
                    name="Stripe",
                    entity_type="company",
                    description="Online payment processing platform",
                    additional_attributes=AdditionalAttributes(
                        company_attributes=CompanyAttributes(
                            domain="stripe.com",
                            key_persons=["Patrick Collison", "John Collison"],
                        ),
                    ),
                ),
            ],
        )
        """
        _response = self._raw_client.create_entities_batch(entities=entities, request_options=request_options)
        return _response.data

    def get_entity(self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> EntityResponse:
        """
        Returns a single entity by ID with all attributes and current status.

        Parameters
        ----------
        entity_id : str
            Unique entity identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityResponse
            Full entity object with all attributes and metadata.

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.entities.get_entity(
            entity_id="854198fa-f702-49db-a381-0427fa87f173",
        )
        """
        _response = self._raw_client.get_entity(entity_id, request_options=request_options)
        return _response.data

    def delete_entity(self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes an entity. The entity is removed from all
        datasets and the search index. This operation cannot be undone.

        Parameters
        ----------
        entity_id : str
            Unique entity identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.entities.delete_entity(
            entity_id="854198fa-f702-49db-a381-0427fa87f173",
        )
        """
        _response = self._raw_client.delete_entity(entity_id, request_options=request_options)
        return _response.data

    def update_entity(
        self,
        entity_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        additional_attributes: typing.Optional[AdditionalAttributes] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityResponse:
        """
        Updates one or more fields of an existing entity.

        Parameters
        ----------
        entity_id : str
            Unique entity identifier.

        name : typing.Optional[str]
            Updated entity name.

        description : typing.Optional[str]
            Updated description.

        additional_attributes : typing.Optional[AdditionalAttributes]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityResponse
            Full entity object with all attributes and metadata.

        Examples
        --------
        from newscatcher_catchall import (
            AdditionalAttributes,
            CatchAllApi,
            CompanyAttributes,
        )

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.entities.update_entity(
            entity_id="854198fa-f702-49db-a381-0427fa87f173",
            description="Updated description",
            additional_attributes=AdditionalAttributes(
                company_attributes=CompanyAttributes(
                    alternative_names=["NC", "NewsCatcher API", "NCA"],
                ),
            ),
        )
        """
        _response = self._raw_client.update_entity(
            entity_id,
            name=name,
            description=description,
            additional_attributes=additional_attributes,
            request_options=request_options,
        )
        return _response.data


class AsyncEntitiesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEntitiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEntitiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEntitiesClient
        """
        return self._raw_client

    async def list_entities(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[EntityStatus] = None,
        entity_type: typing.Optional[EntityType] = None,
        sort_by: typing.Optional[EntitySortBy] = None,
        sort_order: typing.Optional[SortOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityListResponse:
        """
        Returns a paginated list of entities belonging to the authenticated
        organization. Supports filtering by status and entity type, and
        sorting by name, status, or creation date.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of entities per page.

        search : typing.Optional[str]
            Filter entities by name (case-insensitive substring match).

        status : typing.Optional[EntityStatus]

        entity_type : typing.Optional[EntityType]

        sort_by : typing.Optional[EntitySortBy]

        sort_order : typing.Optional[SortOrder]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityListResponse
            Paginated list of entities.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.entities.list_entities(
                search="NewsCatcher",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_entities(
            page=page,
            page_size=page_size,
            search=search,
            status=status,
            entity_type=entity_type,
            sort_by=sort_by,
            sort_order=sort_order,
            request_options=request_options,
        )
        return _response.data

    async def create_entity(
        self,
        *,
        name: str,
        entity_type: typing.Optional[EntityType] = OMIT,
        description: typing.Optional[str] = OMIT,
        additional_attributes: typing.Optional[AdditionalAttributes] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateEntityResponse:
        """
        Creates a new company entity and begins background enrichment.

        The entity status starts as `pending` and transitions to `ready` once
        enrichment completes. Provide as much identifying information as
        possible — `domain` is the highest-signal field because it is
        unambiguous.

        Parameters
        ----------
        name : str
            The company or person name. Required and must be non-empty.

        entity_type : typing.Optional[EntityType]

        description : typing.Optional[str]
            Free-text description of the entity used for disambiguation when similar names exist.

        additional_attributes : typing.Optional[AdditionalAttributes]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateEntityResponse
            Entity created successfully.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import (
            AdditionalAttributes,
            AsyncCatchAllApi,
            CompanyAttributes,
        )

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.entities.create_entity(
                name="NewsCatcher",
                entity_type="company",
                description="AI-powered news data provider",
                additional_attributes=AdditionalAttributes(
                    company_attributes=CompanyAttributes(
                        domain="newscatcherapi.com",
                        key_persons=["Artem Bugara", "Maksym Sugonyaka"],
                        alternative_names=["NC", "NewsCatcher API"],
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_entity(
            name=name,
            entity_type=entity_type,
            description=description,
            additional_attributes=additional_attributes,
            request_options=request_options,
        )
        return _response.data

    async def create_entities_batch(
        self, *, entities: typing.Sequence[CreateEntityRequest], request_options: typing.Optional[RequestOptions] = None
    ) -> CreateEntitiesBatchResponse:
        """
        Creates multiple entities in a single request. Each entity is
        processed independently — a failure in one does not affect others.

        Returns an array of `{id, status}` objects in the same order as
        the input array.

        Parameters
        ----------
        entities : typing.Sequence[CreateEntityRequest]
            Array of entities to create. Each item follows the same schema
            as single entity creation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateEntitiesBatchResponse
            Batch of entities created successfully.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import (
            AdditionalAttributes,
            AsyncCatchAllApi,
            CompanyAttributes,
            CreateEntityRequest,
        )

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.entities.create_entities_batch(
                entities=[
                    CreateEntityRequest(
                        name="OpenAI",
                        entity_type="company",
                        description="Artificial intelligence research company",
                        additional_attributes=AdditionalAttributes(
                            company_attributes=CompanyAttributes(
                                domain="openai.com",
                                key_persons=["Sam Altman"],
                                alternative_names=["Open AI"],
                            ),
                        ),
                    ),
                    CreateEntityRequest(
                        name="Stripe",
                        entity_type="company",
                        description="Online payment processing platform",
                        additional_attributes=AdditionalAttributes(
                            company_attributes=CompanyAttributes(
                                domain="stripe.com",
                                key_persons=["Patrick Collison", "John Collison"],
                            ),
                        ),
                    ),
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_entities_batch(entities=entities, request_options=request_options)
        return _response.data

    async def get_entity(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EntityResponse:
        """
        Returns a single entity by ID with all attributes and current status.

        Parameters
        ----------
        entity_id : str
            Unique entity identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityResponse
            Full entity object with all attributes and metadata.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.entities.get_entity(
                entity_id="854198fa-f702-49db-a381-0427fa87f173",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_entity(entity_id, request_options=request_options)
        return _response.data

    async def delete_entity(self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes an entity. The entity is removed from all
        datasets and the search index. This operation cannot be undone.

        Parameters
        ----------
        entity_id : str
            Unique entity identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.entities.delete_entity(
                entity_id="854198fa-f702-49db-a381-0427fa87f173",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_entity(entity_id, request_options=request_options)
        return _response.data

    async def update_entity(
        self,
        entity_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        additional_attributes: typing.Optional[AdditionalAttributes] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityResponse:
        """
        Updates one or more fields of an existing entity.

        Parameters
        ----------
        entity_id : str
            Unique entity identifier.

        name : typing.Optional[str]
            Updated entity name.

        description : typing.Optional[str]
            Updated description.

        additional_attributes : typing.Optional[AdditionalAttributes]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityResponse
            Full entity object with all attributes and metadata.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import (
            AdditionalAttributes,
            AsyncCatchAllApi,
            CompanyAttributes,
        )

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.entities.update_entity(
                entity_id="854198fa-f702-49db-a381-0427fa87f173",
                description="Updated description",
                additional_attributes=AdditionalAttributes(
                    company_attributes=CompanyAttributes(
                        alternative_names=["NC", "NewsCatcher API", "NCA"],
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_entity(
            entity_id,
            name=name,
            description=description,
            additional_attributes=additional_attributes,
            request_options=request_options,
        )
        return _response.data
