# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..types.additional_attributes import AdditionalAttributes
from ..types.create_entities_batch_response import CreateEntitiesBatchResponse
from ..types.create_entity_request import CreateEntityRequest
from ..types.create_entity_response import CreateEntityResponse
from ..types.entity_list_response import EntityListResponse
from ..types.entity_response import EntityResponse
from ..types.entity_sort_by import EntitySortBy
from ..types.entity_status import EntityStatus
from ..types.entity_type import EntityType
from ..types.error import Error
from ..types.sort_order import SortOrder
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawEntitiesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_entities(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[EntityStatus] = None,
        entity_type: typing.Optional[EntityType] = None,
        sort_by: typing.Optional[EntitySortBy] = None,
        sort_order: typing.Optional[SortOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[EntityListResponse]:
        """
        Returns a paginated list of entities belonging to the authenticated
        organization. Supports filtering by status and entity type, and
        sorting by name, status, or creation date.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of entities per page.

        search : typing.Optional[str]
            Filter entities by name (case-insensitive substring match).

        status : typing.Optional[EntityStatus]

        entity_type : typing.Optional[EntityType]

        sort_by : typing.Optional[EntitySortBy]

        sort_order : typing.Optional[SortOrder]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EntityListResponse]
            Paginated list of entities.
        """
        _response = self._client_wrapper.httpx_client.request(
            "catchAll/entities",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "search": search,
                "status": status,
                "entity_type": entity_type,
                "sort_by": sort_by,
                "sort_order": sort_order,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EntityListResponse,
                    parse_obj_as(
                        type_=EntityListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_entity(
        self,
        *,
        name: str,
        entity_type: typing.Optional[EntityType] = OMIT,
        description: typing.Optional[str] = OMIT,
        additional_attributes: typing.Optional[AdditionalAttributes] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateEntityResponse]:
        """
        Creates a new company entity and begins background enrichment.

        The entity status starts as `pending` and transitions to `ready` once
        enrichment completes. Provide as much identifying information as
        possible — `domain` is the highest-signal field because it is
        unambiguous.

        Parameters
        ----------
        name : str
            The company or person name. Required and must be non-empty.

        entity_type : typing.Optional[EntityType]

        description : typing.Optional[str]
            Free-text description of the entity used for disambiguation when similar names exist.

        additional_attributes : typing.Optional[AdditionalAttributes]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateEntityResponse]
            Entity created successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            "catchAll/entities",
            method="POST",
            json={
                "name": name,
                "entity_type": entity_type,
                "description": description,
                "additional_attributes": convert_and_respect_annotation_metadata(
                    object_=additional_attributes, annotation=AdditionalAttributes, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateEntityResponse,
                    parse_obj_as(
                        type_=CreateEntityResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_entities_batch(
        self, *, entities: typing.Sequence[CreateEntityRequest], request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CreateEntitiesBatchResponse]:
        """
        Creates multiple entities in a single request. Each entity is
        processed independently — a failure in one does not affect others.

        Returns an array of `{id, status}` objects in the same order as
        the input array.

        Parameters
        ----------
        entities : typing.Sequence[CreateEntityRequest]
            Array of entities to create. Each item follows the same schema
            as single entity creation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateEntitiesBatchResponse]
            Batch of entities created successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            "catchAll/entities/batch",
            method="POST",
            json={
                "entities": convert_and_respect_annotation_metadata(
                    object_=entities, annotation=typing.Sequence[CreateEntityRequest], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateEntitiesBatchResponse,
                    parse_obj_as(
                        type_=CreateEntitiesBatchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_entity(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[EntityResponse]:
        """
        Returns a single entity by ID with all attributes and current status.

        Parameters
        ----------
        entity_id : str
            Unique entity identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EntityResponse]
            Full entity object with all attributes and metadata.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/entities/{encode_path_param(entity_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EntityResponse,
                    parse_obj_as(
                        type_=EntityResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_entity(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Permanently deletes an entity. The entity is removed from all
        datasets and the search index. This operation cannot be undone.

        Parameters
        ----------
        entity_id : str
            Unique entity identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/entities/{encode_path_param(entity_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_entity(
        self,
        entity_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        additional_attributes: typing.Optional[AdditionalAttributes] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[EntityResponse]:
        """
        Updates one or more fields of an existing entity.

        Parameters
        ----------
        entity_id : str
            Unique entity identifier.

        name : typing.Optional[str]
            Updated entity name.

        description : typing.Optional[str]
            Updated description.

        additional_attributes : typing.Optional[AdditionalAttributes]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EntityResponse]
            Full entity object with all attributes and metadata.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/entities/{encode_path_param(entity_id)}",
            method="PATCH",
            json={
                "name": name,
                "description": description,
                "additional_attributes": convert_and_respect_annotation_metadata(
                    object_=additional_attributes, annotation=AdditionalAttributes, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EntityResponse,
                    parse_obj_as(
                        type_=EntityResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawEntitiesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_entities(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[EntityStatus] = None,
        entity_type: typing.Optional[EntityType] = None,
        sort_by: typing.Optional[EntitySortBy] = None,
        sort_order: typing.Optional[SortOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[EntityListResponse]:
        """
        Returns a paginated list of entities belonging to the authenticated
        organization. Supports filtering by status and entity type, and
        sorting by name, status, or creation date.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of entities per page.

        search : typing.Optional[str]
            Filter entities by name (case-insensitive substring match).

        status : typing.Optional[EntityStatus]

        entity_type : typing.Optional[EntityType]

        sort_by : typing.Optional[EntitySortBy]

        sort_order : typing.Optional[SortOrder]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EntityListResponse]
            Paginated list of entities.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "catchAll/entities",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "search": search,
                "status": status,
                "entity_type": entity_type,
                "sort_by": sort_by,
                "sort_order": sort_order,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EntityListResponse,
                    parse_obj_as(
                        type_=EntityListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_entity(
        self,
        *,
        name: str,
        entity_type: typing.Optional[EntityType] = OMIT,
        description: typing.Optional[str] = OMIT,
        additional_attributes: typing.Optional[AdditionalAttributes] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateEntityResponse]:
        """
        Creates a new company entity and begins background enrichment.

        The entity status starts as `pending` and transitions to `ready` once
        enrichment completes. Provide as much identifying information as
        possible — `domain` is the highest-signal field because it is
        unambiguous.

        Parameters
        ----------
        name : str
            The company or person name. Required and must be non-empty.

        entity_type : typing.Optional[EntityType]

        description : typing.Optional[str]
            Free-text description of the entity used for disambiguation when similar names exist.

        additional_attributes : typing.Optional[AdditionalAttributes]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateEntityResponse]
            Entity created successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "catchAll/entities",
            method="POST",
            json={
                "name": name,
                "entity_type": entity_type,
                "description": description,
                "additional_attributes": convert_and_respect_annotation_metadata(
                    object_=additional_attributes, annotation=AdditionalAttributes, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateEntityResponse,
                    parse_obj_as(
                        type_=CreateEntityResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_entities_batch(
        self, *, entities: typing.Sequence[CreateEntityRequest], request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CreateEntitiesBatchResponse]:
        """
        Creates multiple entities in a single request. Each entity is
        processed independently — a failure in one does not affect others.

        Returns an array of `{id, status}` objects in the same order as
        the input array.

        Parameters
        ----------
        entities : typing.Sequence[CreateEntityRequest]
            Array of entities to create. Each item follows the same schema
            as single entity creation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateEntitiesBatchResponse]
            Batch of entities created successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "catchAll/entities/batch",
            method="POST",
            json={
                "entities": convert_and_respect_annotation_metadata(
                    object_=entities, annotation=typing.Sequence[CreateEntityRequest], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateEntitiesBatchResponse,
                    parse_obj_as(
                        type_=CreateEntitiesBatchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_entity(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[EntityResponse]:
        """
        Returns a single entity by ID with all attributes and current status.

        Parameters
        ----------
        entity_id : str
            Unique entity identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EntityResponse]
            Full entity object with all attributes and metadata.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/entities/{encode_path_param(entity_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EntityResponse,
                    parse_obj_as(
                        type_=EntityResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_entity(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Permanently deletes an entity. The entity is removed from all
        datasets and the search index. This operation cannot be undone.

        Parameters
        ----------
        entity_id : str
            Unique entity identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/entities/{encode_path_param(entity_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_entity(
        self,
        entity_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        additional_attributes: typing.Optional[AdditionalAttributes] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[EntityResponse]:
        """
        Updates one or more fields of an existing entity.

        Parameters
        ----------
        entity_id : str
            Unique entity identifier.

        name : typing.Optional[str]
            Updated entity name.

        description : typing.Optional[str]
            Updated description.

        additional_attributes : typing.Optional[AdditionalAttributes]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EntityResponse]
            Full entity object with all attributes and metadata.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/entities/{encode_path_param(entity_id)}",
            method="PATCH",
            json={
                "name": name,
                "description": description,
                "additional_attributes": convert_and_respect_annotation_metadata(
                    object_=additional_attributes, annotation=AdditionalAttributes, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EntityResponse,
                    parse_obj_as(
                        type_=EntityResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
