# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ApiKeyAuthResponseDto(UniversalBaseModel):
    """
    API key authentication as returned in webhook responses. The key value is masked.
    """

    header: typing.Optional[str] = pydantic.Field(default=None)
    """
    HTTP header name for the API key. Returned in full.
    """

    value: typing.Optional[str] = pydantic.Field(default=None)
    """
    Masked API key value. Never returned in full.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
