# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_resource_mapping_response_dto import WebhookResourceMappingResponseDto


class AssignWebhookResourceResponseDto(UniversalBaseModel):
    success: bool = pydantic.Field()
    """
    True if the operation succeeded; false otherwise.
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable result message.
    """

    already_existed: typing.Optional[bool] = pydantic.Field(default=None)
    """
    True if the assignment already existed before this request.
    """

    mapping: typing.Optional[WebhookResourceMappingResponseDto] = pydantic.Field(default=None)
    """
    The created or existing resource mapping.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
