# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BasicAuthResponseDto(UniversalBaseModel):
    """
    Basic authentication as returned in webhook responses. The password is masked.
    """

    username: typing.Optional[str] = pydantic.Field(default=None)
    """
    Basic auth username. Returned in full.
    """

    password: typing.Optional[str] = pydantic.Field(default=None)
    """
    Masked password. Never returned in full.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
