# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Citation(UniversalBaseModel):
    title: str = pydantic.Field()
    """
    The title of the source document.
    """

    link: str = pydantic.Field()
    """
    URL to the source document.
    """

    published_date: dt.datetime = pydantic.Field()
    """
    The publication date of the source document in ISO 8601 format (UTC timezone).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
