# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .company_enrichment_output_metadata_domain_url_confidence import CompanyEnrichmentOutputMetadataDomainUrlConfidence


class CompanyEnrichmentOutputMetadata(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Normalized company name.
    """

    domain_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company website domain if resolved, otherwise null.
    """

    domain_url_confidence: typing.Optional[CompanyEnrichmentOutputMetadataDomainUrlConfidence] = pydantic.Field(
        default=None
    )
    """
    Confidence level for the domain URL resolution.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
