# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ConnectedEntity(UniversalBaseModel):
    """
    A company entity matched to a record in a Company Watchlist job, with
    a relevance score and explanation.

    Only entities with `ed_score` ≥ 1 appear in results. Entities scored
    0 are filtered out before the response is returned.
    """

    entity_id: str = pydantic.Field()
    """
    Unique identifier of the matched entity.
    """

    name: str = pydantic.Field()
    """
    Name of the matched entity.
    """

    ed_score: int = pydantic.Field()
    """
    Relevance score indicating how directly the entity is associated
    with this event.
    
    | Score | Meaning |
    |-------|---------|
    | 10 | Direct mention, critical event (merger, CEO change, major lawsuit) |
    | 7–9 | Major impact (earnings, product launch, senior hire) |
    | 4–6 | Routine update (minor product news, mid-level changes) |
    | 1–3 | Indirect mention (listed with others, stock noise) |
    """

    relation: str = pydantic.Field()
    """
    Short explanation (up to 100 characters) of why this entity is
    associated with the event.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
