# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_entity_response import CreateEntityResponse


class CreateEntitiesBatchResponse(UniversalBaseModel):
    entities: typing.List[CreateEntityResponse] = pydantic.Field()
    """
    Array of created entity stubs in the same order as the input.
    """

    count: int = pydantic.Field()
    """
    Total number of entities created.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
