# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .delivery_history_item_dto import DeliveryHistoryItemDto
from .mappable_resource_type import MappableResourceType


class DeliveryHistoryResponseDto(UniversalBaseModel):
    resource_type: MappableResourceType = pydantic.Field()
    """
    Type of the queried resource.
    """

    resource_id: str = pydantic.Field()
    """
    Identifier of the queried resource.
    """

    total: int = pydantic.Field()
    """
    Total number of delivery records for this resource.
    """

    page: int = pydantic.Field()
    """
    Current page number.
    """

    page_size: int = pydantic.Field()
    """
    Number of records per page.
    """

    total_pages: int = pydantic.Field()
    """
    Total number of pages available.
    """

    items: typing.List[DeliveryHistoryItemDto] = pydantic.Field()
    """
    Delivery records on this page, ordered by timestamp descending.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
