# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .enrichment_type import EnrichmentType


class EnrichmentSchema(UniversalBaseModel):
    """
    Schema for a single enrichment field that extracts structured data.

    Enrichments are applied during the enriching stage to extract information from validated clusters.
    """

    name: str = pydantic.Field()
    """
    Enrichment field name (snake_case recommended).
    """

    description: str = pydantic.Field()
    """
    What information this field extracts.
    """

    type: EnrichmentType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
