# This file was auto-generated by Fern from our API Definition.

import typing

EnrichmentType = typing.Union[typing.Literal["text", "number", "date", "option", "url", "dict", "company"], typing.Any]
