# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .company_attributes import CompanyAttributes
from .entity_status import EntityStatus
from .entity_type import EntityType


class EntitySummary(UniversalBaseModel):
    """
    Abbreviated entity object returned when listing entities within a
    dataset. Uses a flat `attributes` key rather than the nested
    `additional_attributes.company_attributes` structure used in
    standalone entity endpoints.
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the entity.
    """

    name: str = pydantic.Field()
    """
    Entity name.
    """

    entity_type: EntityType
    status: EntityStatus
    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Free-text description.
    """

    attributes: typing.Optional[CompanyAttributes] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
