# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .additional_attributes import AdditionalAttributes
from .entity_status import EntityStatus
from .entity_type import EntityType


class EntityResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier of the entity.
    """

    entity_type: EntityType
    organization_id: str = pydantic.Field()
    """
    Organization that owns this entity.
    """

    name: str = pydantic.Field()
    """
    Entity name.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Free-text description.
    """

    additional_attributes: typing.Optional[AdditionalAttributes] = None
    status: EntityStatus
    created_by_user_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the user who created this entity.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO 8601 timestamp of when the entity was created. Returned without timezone offset (server-local time).
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO 8601 timestamp of when the entity was last updated. Returned without timezone offset (server-local time).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
