# This file was auto-generated by Fern from our API Definition.

import typing

IssueType = typing.Union[
    typing.Literal[
        "missing_event_type",
        "too_vague",
        "too_specific",
        "wrong_timeframe",
        "static_content",
        "article_request",
        "multiple_event_types",
        "too_short",
        "too_long",
    ],
    typing.Any,
]
