# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .public_job_status import PublicJobStatus


class JobStep(UniversalBaseModel):
    status: PublicJobStatus
    order: int = pydantic.Field()
    """
    Sequential position of this step in the pipeline (1-7).
    """

    completed: bool = pydantic.Field()
    """
    True if this step has finished processing; false otherwise.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
