# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_response_dto import WebhookResponseDto


class ListWebhooksResponseDto(UniversalBaseModel):
    total: int = pydantic.Field()
    """
    Total number of webhooks in the organization.
    """

    page: int = pydantic.Field()
    """
    Current page number.
    """

    page_size: int = pydantic.Field()
    """
    Number of webhooks per page.
    """

    total_pages: int = pydantic.Field()
    """
    Total number of pages available.
    """

    webhooks: typing.List[WebhookResponseDto] = pydantic.Field()
    """
    Webhooks on this page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
