# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .monitor_list_item_dto import MonitorListItemDto


class ListMonitorsResponseDto(UniversalBaseModel):
    total: int = pydantic.Field()
    """
    Total number of monitors for this user.
    """

    page: int = pydantic.Field()
    """
    Current page number.
    """

    page_size: int = pydantic.Field()
    """
    Number of monitors per page.
    """

    total_pages: int = pydantic.Field()
    """
    Total number of pages available.
    """

    monitors: typing.List[MonitorListItemDto] = pydantic.Field()
    """
    Array of monitor summaries.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
