# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .citation import Citation


class MonitorCitation(Citation):
    """
    Citation with monitor-specific metadata. Used in monitor results and webhook payloads.
    Extends base citation with tracking information for job_id and timestamps.
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the document in the search index.
    """

    job_id: str = pydantic.Field()
    """
    Job ID that found this citation.
    """

    added_on: dt.datetime = pydantic.Field()
    """
    The date when the citation was added to the record in ISO 8601 format with UTC timezone.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
