# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .sharing_info import SharingInfo
from .webhook_dto import WebhookDto


class MonitorListItemDto(UniversalBaseModel):
    monitor_id: str = pydantic.Field()
    """
    Monitor identifier.
    """

    reference_job_id: str = pydantic.Field()
    """
    Job identifier used as a reference for this monitor.
    """

    reference_job_query: str = pydantic.Field()
    """
    Plain text query from the reference job.
    """

    enabled: bool = pydantic.Field()
    """
    True if the monitor is currently active; false otherwise.
    """

    schedule: typing.Optional[str] = pydantic.Field(default=None)
    """
    Cron expression for monitor schedule.
    """

    schedule_human_readable: typing.Optional[str] = pydantic.Field(default=None)
    """
    The monitor schedule in a plain text format.
    """

    timezone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Timezone for schedule execution.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The date when the monitor was created.
    """

    webhook: typing.Optional[WebhookDto] = pydantic.Field(default=None)
    """
    Webhook configuration for this monitor, or null if not set.
    """

    user_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Masked API key associated with this monitor.
    """

    sharing_info: typing.Optional[SharingInfo] = pydantic.Field(default=None)
    """
    Present when this monitor was shared with the authenticated user. Omitted when the user owns the monitor.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
