# This file was auto-generated by Fern from our API Definition.

import typing

ProjectResourceType = typing.Union[typing.Literal["job", "monitor", "dataset", "monitor_group", "webhook"], typing.Any]
