# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ProjectResponseDto(UniversalBaseModel):
    success: bool = pydantic.Field()
    """
    True if the operation succeeded; false otherwise.
    """

    message: str = pydantic.Field()
    """
    Human-readable result message.
    """

    project_id: str = pydantic.Field()
    """
    Project identifier.
    """

    name: str = pydantic.Field()
    """
    Project name.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Project description.
    """

    resources_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of resources assigned to this project.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Project creation timestamp.
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Timestamp of the last update.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
