# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .project_overview_counts_dto import ProjectOverviewCountsDto


class ProjectOverviewResponseDtoOverview(UniversalBaseModel):
    """
    Resource counts grouped by type.
    """

    jobs: ProjectOverviewCountsDto
    monitors: ProjectOverviewCountsDto
    datasets: ProjectOverviewCountsDto
    monitor_groups: ProjectOverviewCountsDto

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
