# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .project_resource_type import ProjectResourceType


class ProjectResourceDto(UniversalBaseModel):
    """
    A resource assigned to a project.
    """

    resource_type: ProjectResourceType
    resource_id: str = pydantic.Field()
    """
    Resource identifier.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Resource display name. For jobs, this is the original query
    string. For monitors and datasets, this is the resource name.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Resource creation timestamp.
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Additional resource-specific metadata.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
