# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .connected_dataset import ConnectedDataset
from .pull_job_response_dto_date_range import PullJobResponseDtoDateRange
from .pull_job_response_dto_mode import PullJobResponseDtoMode
from .record import Record
from .sharing_info import SharingInfo


class PullJobResponseDto(UniversalBaseModel):
    job_id: str = pydantic.Field()
    """
    Job identifier.
    """

    query: typing.Optional[str] = pydantic.Field(default=None)
    """
    Original plain text query.
    """

    context: typing.Optional[str] = pydantic.Field(default=None)
    """
    Context provided with the query.
    """

    validators: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Validators applied to filter results.
    """

    enrichments: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Enrichment fields used for data extraction.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Job status.
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message if the job failed. Null for successful jobs.
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Record limit for this job. Reflects the value specified at submit time, or the plan default if no limit was provided.
    """

    duration: typing.Optional[str] = pydantic.Field(default=None)
    """
    Total time taken to process the job.
    """

    candidate_records: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of distinct event clusters identified. Compare with `progress_validated` to estimate how many candidates remain unprocessed for job continuation.
    """

    valid_records: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of validated records extracted.
    """

    progress_validated: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of candidate clusters that have been validated during processing.
    
    The system process data in batches. This field tracks how many `candidate_records` have been checked against validation criteria so far.
    """

    date_range: typing.Optional[PullJobResponseDtoDateRange] = None
    page: typing.Optional[int] = pydantic.Field(default=None)
    """
    The current page number.
    """

    page_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of records per page.
    """

    total_pages: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of pages available.
    """

    mode: typing.Optional[PullJobResponseDtoMode] = pydantic.Field(default=None)
    """
    Processing mode used for this job.
    """

    connected_datasets: typing.Optional[typing.List[ConnectedDataset]] = pydantic.Field(default=None)
    """
    Datasets used to narrow retrieval scope, each with `id` and `name`.
    """

    is_all_news_query: typing.Optional[bool] = pydantic.Field(default=None)
    """
    True when the query was submitted as an all-news (watchlist-generic) query.
    """

    sharing_info: typing.Optional[SharingInfo] = pydantic.Field(default=None)
    """
    Present when the job was shared with the authenticated user by another organization member. `null` when the user owns the job.
    """

    all_records: typing.Optional[typing.List[Record]] = pydantic.Field(default=None)
    """
    Array of extracted records with structured data and citations.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
