# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .base_record import BaseRecord
from .citation import Citation
from .connected_entity import ConnectedEntity


class Record(BaseRecord):
    citations: typing.List[Citation] = pydantic.Field()
    """
    Source documents that were used to extract this record.
    """

    connected_entities: typing.Optional[typing.List[ConnectedEntity]] = pydantic.Field(default=None)
    """
    Entities from the connected dataset that are relevant to this record.
    Only present when the job was submitted with `connected_dataset_ids`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
