# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .issue_type import IssueType


class Suggestion(UniversalBaseModel):
    """
    Actionable recommendation for improving a query.
    """

    issue: IssueType = pydantic.Field()
    """
    The issue this suggestion addresses.
    """

    message: str = pydantic.Field()
    """
    Specific guidance for improving the query.
    """

    example: typing.Optional[str] = pydantic.Field(default=None)
    """
    Revised query demonstrating the suggested improvement.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
