# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TestWebhookResponseDto(UniversalBaseModel):
    success: bool = pydantic.Field()
    """
    True if the test delivery received a 2xx response; false otherwise.
    """

    message: str = pydantic.Field()
    """
    Human-readable result message.
    """

    http_status_code: typing.Optional[int] = pydantic.Field(default=None)
    """
    HTTP status code returned by the webhook endpoint.
    """

    response_body: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    Response body returned by the webhook endpoint. Type varies by target.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
