# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .sharing_info import SharingInfo
from .user_job_mode import UserJobMode


class UserJob(UniversalBaseModel):
    job_id: str = pydantic.Field()
    """
    Job identifier.
    """

    query: str = pydantic.Field()
    """
    Plain text query for this job.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Job creation timestamp in ISO 8601 format.
    """

    status: str = pydantic.Field()
    """
    Current processing status of the job.
    """

    mode: typing.Optional[UserJobMode] = pydantic.Field(default=None)
    """
    Processing mode used for this job.
    """

    sharing_info: typing.Optional[SharingInfo] = pydantic.Field(default=None)
    """
    Present when this job is shared with the authenticated user. Omitted when the user owns the job.
    """

    user_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Masked API key that created this job.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
