# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ValidatorSchema(UniversalBaseModel):
    """
    Schema for a single validator that filters article clusters.

    Validators are applied during the enriching stage to determine which clusters are relevant.
    """

    name: str = pydantic.Field()
    """
    Validator field name (snake_case recommended).
    """

    description: str = pydantic.Field()
    """
    What this validator checks for in the article.
    """

    type: typing.Optional[typing.Literal["boolean"]] = pydantic.Field(default=None)
    """
    Validator type (currently only boolean supported).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
