# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WebhookResourceMappingResponseDto(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Mapping identifier.
    """

    webhook_id: str = pydantic.Field()
    """
    Webhook identifier.
    """

    resource_type: str = pydantic.Field()
    """
    Type of the assigned resource.
    """

    resource_id: str = pydantic.Field()
    """
    Identifier of the assigned resource.
    """

    assigned_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Timestamp when the resource was assigned in ISO 8601 format with UTC timezone.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
