# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WebhookResponseDtoAuth_Bearer(UniversalBaseModel):
    type: typing.Literal["bearer"] = "bearer"
    token: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class WebhookResponseDtoAuth_ApiKey(UniversalBaseModel):
    type: typing.Literal["api_key"] = "api_key"
    header: typing.Optional[str] = None
    value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class WebhookResponseDtoAuth_Basic(UniversalBaseModel):
    type: typing.Literal["basic"] = "basic"
    username: typing.Optional[str] = None
    password: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


WebhookResponseDtoAuth = typing_extensions.Annotated[
    typing.Union[WebhookResponseDtoAuth_Bearer, WebhookResponseDtoAuth_ApiKey, WebhookResponseDtoAuth_Basic],
    pydantic.Field(discriminator="type"),
]
