# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateWebhookRequestDtoAuth_Bearer(UniversalBaseModel):
    """
    Authentication forwarded with each delivery. Supported types:
    - `bearer`: Adds an `Authorization: Bearer <token>` header.
    - `api_key`: Adds a custom header with the specified name and value.
    - `basic`: Adds an `Authorization: Basic <credentials>` header.
    """

    type: typing.Literal["bearer"] = "bearer"
    token: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CreateWebhookRequestDtoAuth_ApiKey(UniversalBaseModel):
    """
    Authentication forwarded with each delivery. Supported types:
    - `bearer`: Adds an `Authorization: Bearer <token>` header.
    - `api_key`: Adds a custom header with the specified name and value.
    - `basic`: Adds an `Authorization: Basic <credentials>` header.
    """

    type: typing.Literal["api_key"] = "api_key"
    header: str
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CreateWebhookRequestDtoAuth_Basic(UniversalBaseModel):
    """
    Authentication forwarded with each delivery. Supported types:
    - `bearer`: Adds an `Authorization: Bearer <token>` header.
    - `api_key`: Adds a custom header with the specified name and value.
    - `basic`: Adds an `Authorization: Basic <credentials>` header.
    """

    type: typing.Literal["basic"] = "basic"
    username: str
    password: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


CreateWebhookRequestDtoAuth = typing_extensions.Annotated[
    typing.Union[
        CreateWebhookRequestDtoAuth_Bearer, CreateWebhookRequestDtoAuth_ApiKey, CreateWebhookRequestDtoAuth_Basic
    ],
    pydantic.Field(discriminator="type"),
]
