# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.context import Context
from ..types.continue_response_dto import ContinueResponseDto
from ..types.delete_job_response_dto import DeleteJobResponseDto
from ..types.end_date import EndDate
from ..types.enrichment_schema import EnrichmentSchema
from ..types.entity_association_type import EntityAssociationType
from ..types.error import Error
from ..types.initialize_response_dto import InitializeResponseDto
from ..types.limit import Limit
from ..types.list_user_jobs_response_dto import ListUserJobsResponseDto
from ..types.ownership_filter import OwnershipFilter
from ..types.pull_job_response_dto import PullJobResponseDto
from ..types.query import Query
from ..types.start_date import StartDate
from ..types.status_response_dto import StatusResponseDto
from ..types.submit_response_dto import SubmitResponseDto
from ..types.validate_query_response_dto import ValidateQueryResponseDto
from ..types.validation_error_response import ValidationErrorResponse
from ..types.validator_schema import ValidatorSchema
from .types.submit_request_dto_mode import SubmitRequestDtoMode
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawJobsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_user_jobs(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        ownership: typing.Optional[OwnershipFilter] = None,
        project_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListUserJobsResponseDto]:
        """
        Returns all jobs created by the authenticated user.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of records per page.

        search : typing.Optional[str]
            Filter results by text (case-insensitive substring match).

        ownership : typing.Optional[OwnershipFilter]

        project_id : typing.Optional[str]
            Filter results to resources belonging to this project.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListUserJobsResponseDto]
            User jobs retrieved successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "catchAll/jobs/user",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "search": search,
                "ownership": ownership,
                "project_id": project_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListUserJobsResponseDto,
                    parse_obj_as(
                        type_=ListUserJobsResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def validate_query(
        self, *, query: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ValidateQueryResponseDto]:
        """
        Checks whether a query is well-formed and likely to produce good results before submitting a job.

        Returns a quality assessment with a status level, identified issues, and actionable suggestions.

        Parameters
        ----------
        query : str
            Plain text query to validate.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ValidateQueryResponseDto]
            Query validation result.
        """
        _response = self._client_wrapper.httpx_client.request(
            "catchAll/validate",
            method="POST",
            json={
                "query": query,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ValidateQueryResponseDto,
                    parse_obj_as(
                        type_=ValidateQueryResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def initialize(
        self,
        *,
        query: Query,
        context: typing.Optional[Context] = OMIT,
        connected_dataset_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        fetch_all_watchlist_news: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[InitializeResponseDto]:
        """
        Get suggested validators, enrichments, and date ranges for a query.

        Parameters
        ----------
        query : Query

        context : typing.Optional[Context]

        connected_dataset_ids : typing.Optional[typing.Sequence[str]]
            Optional list of watchlist dataset IDs connected to this job.

        fetch_all_watchlist_news : typing.Optional[bool]
            When true, returns generic news validators and enrichments suitable for
            watchlist-based article collection instead of query-specific fields.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[InitializeResponseDto]
            Suggestions retrieved successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "catchAll/initialize",
            method="POST",
            json={
                "query": query,
                "context": context,
                "connected_dataset_ids": connected_dataset_ids,
                "fetch_all_watchlist_news": fetch_all_watchlist_news,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    InitializeResponseDto,
                    parse_obj_as(
                        type_=InitializeResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_job(
        self,
        *,
        query: Query,
        context: typing.Optional[Context] = OMIT,
        limit: typing.Optional[Limit] = OMIT,
        start_date: typing.Optional[StartDate] = OMIT,
        end_date: typing.Optional[EndDate] = OMIT,
        validators: typing.Optional[typing.Sequence[ValidatorSchema]] = OMIT,
        enrichments: typing.Optional[typing.Sequence[EnrichmentSchema]] = OMIT,
        mode: typing.Optional[SubmitRequestDtoMode] = OMIT,
        connected_dataset_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        ed_score_min: typing.Optional[int] = OMIT,
        project_id: typing.Optional[str] = OMIT,
        webhook_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        fetch_all_watchlist_news: typing.Optional[bool] = OMIT,
        ed_association_type: typing.Optional[EntityAssociationType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SubmitResponseDto]:
        """
        Submit a query to create a new processing job.

        Parameters
        ----------
        query : Query

        context : typing.Optional[Context]

        limit : typing.Optional[Limit]

        start_date : typing.Optional[StartDate]

        end_date : typing.Optional[EndDate]

        validators : typing.Optional[typing.Sequence[ValidatorSchema]]
            Custom validators for filtering web page clusters.

            If not provided, validators are generated automatically based on the query.

        enrichments : typing.Optional[typing.Sequence[EnrichmentSchema]]
            Custom enrichment fields for data extraction.

            If not provided, enrichments are generated automatically based on the query.

        mode : typing.Optional[SubmitRequestDtoMode]
            Job processing mode.

            - `base`: Full pipeline with validation and enrichment.
            - `lite`: Lightweight extraction with faster processing. Returns titles and citations only.

        connected_dataset_ids : typing.Optional[typing.Sequence[str]]
            Dataset IDs to connect to the job. When provided, this enables Company Watchlist mode — the job returns only events relevant to companies in the connected datasets. To set the minimum relevance threshold, use `ed_score_min`.

            The dataset must have `latest_status: ready` before the job is submitted. Submitting with a non-existent or inaccessible dataset ID returns `400`.

        ed_score_min : typing.Optional[int]
            The minimum relevance score a connected entity must reach for its record to be included in results.

            Only valid when `connected_dataset_ids` is set; otherwise ignored. Records where no connected entity meets the threshold are excluded entirely.

        project_id : typing.Optional[str]
            Project to assign this job to. The job appears in the project's resource list immediately after submission.

        webhook_ids : typing.Optional[typing.Sequence[str]]
            IDs of webhooks to notify when the job completes. Maximum 5 per job.

        fetch_all_watchlist_news : typing.Optional[bool]
            When true, retrieves all news for connected Company Watchlist entities
            without topic filtering. Requires connected_dataset_ids to be set.

        ed_association_type : typing.Optional[EntityAssociationType]
            Filter events by entity association type. `event_associated` keeps only
            events where the entity is a direct actor. `mention` keeps only events
            where the entity is merely referenced. Only relevant when
            connected_dataset_ids is set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SubmitResponseDto]
            Job created successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "catchAll/submit",
            method="POST",
            json={
                "query": query,
                "context": context,
                "limit": limit,
                "start_date": start_date,
                "end_date": end_date,
                "validators": convert_and_respect_annotation_metadata(
                    object_=validators, annotation=typing.Sequence[ValidatorSchema], direction="write"
                ),
                "enrichments": convert_and_respect_annotation_metadata(
                    object_=enrichments, annotation=typing.Sequence[EnrichmentSchema], direction="write"
                ),
                "mode": mode,
                "connected_dataset_ids": connected_dataset_ids,
                "ed_score_min": ed_score_min,
                "project_id": project_id,
                "webhook_ids": webhook_ids,
                "fetch_all_watchlist_news": fetch_all_watchlist_news,
                "ed_association_type": ed_association_type,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubmitResponseDto,
                    parse_obj_as(
                        type_=SubmitResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_job_status(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[StatusResponseDto]:
        """
        Retrieve the current processing status of a job.

        Parameters
        ----------
        job_id : str
            Unique job identifier returned from [`POST /catchAll/submit`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/jobs/create-job).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[StatusResponseDto]
            Status retrieved successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/status/{encode_path_param(job_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StatusResponseDto,
                    parse_obj_as(
                        type_=StatusResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_job_results(
        self,
        job_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PullJobResponseDto]:
        """
        Retrieve the final results for a completed job.

        Parameters
        ----------
        job_id : str
            Unique job identifier returned from [`POST /catchAll/submit`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/jobs/create-job).

        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of records per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PullJobResponseDto]
            Results retrieved successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/pull/{encode_path_param(job_id)}",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PullJobResponseDto,
                    parse_obj_as(
                        type_=PullJobResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def continue_job(
        self,
        *,
        job_id: str,
        new_limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ContinueResponseDto]:
        """
        Continue an existing job to process more records beyond the initial limit.

        Parameters
        ----------
        job_id : str
            Job identifier of the completed job to continue.

        new_limit : typing.Optional[int]
            New record limit for continued processing. Must be greater than the previous limit. If not provided, defaults to the plan maximum.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ContinueResponseDto]
            Job continuation accepted
        """
        _response = self._client_wrapper.httpx_client.request(
            "catchAll/continue",
            method="POST",
            json={
                "job_id": job_id,
                "new_limit": new_limit,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ContinueResponseDto,
                    parse_obj_as(
                        type_=ContinueResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_job(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DeleteJobResponseDto]:
        """
        Soft-deletes a job. The job is flagged as deleted and no longer appears in list results. The underlying data is retained.

        Only the job owner can delete a job. Returns `404` if the job is not found or does not belong to the authenticated user.

        Deleting an already-deleted job returns `200`.

        Parameters
        ----------
        job_id : str
            Unique job identifier returned from [`POST /catchAll/submit`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/jobs/create-job).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeleteJobResponseDto]
            Job deleted successfully (or already deleted).
        """
        _response = self._client_wrapper.httpx_client.request(
            f"catchAll/jobs/{encode_path_param(job_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeleteJobResponseDto,
                    parse_obj_as(
                        type_=DeleteJobResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawJobsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_user_jobs(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        ownership: typing.Optional[OwnershipFilter] = None,
        project_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListUserJobsResponseDto]:
        """
        Returns all jobs created by the authenticated user.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of records per page.

        search : typing.Optional[str]
            Filter results by text (case-insensitive substring match).

        ownership : typing.Optional[OwnershipFilter]

        project_id : typing.Optional[str]
            Filter results to resources belonging to this project.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListUserJobsResponseDto]
            User jobs retrieved successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "catchAll/jobs/user",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "search": search,
                "ownership": ownership,
                "project_id": project_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListUserJobsResponseDto,
                    parse_obj_as(
                        type_=ListUserJobsResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def validate_query(
        self, *, query: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ValidateQueryResponseDto]:
        """
        Checks whether a query is well-formed and likely to produce good results before submitting a job.

        Returns a quality assessment with a status level, identified issues, and actionable suggestions.

        Parameters
        ----------
        query : str
            Plain text query to validate.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ValidateQueryResponseDto]
            Query validation result.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "catchAll/validate",
            method="POST",
            json={
                "query": query,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ValidateQueryResponseDto,
                    parse_obj_as(
                        type_=ValidateQueryResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def initialize(
        self,
        *,
        query: Query,
        context: typing.Optional[Context] = OMIT,
        connected_dataset_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        fetch_all_watchlist_news: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[InitializeResponseDto]:
        """
        Get suggested validators, enrichments, and date ranges for a query.

        Parameters
        ----------
        query : Query

        context : typing.Optional[Context]

        connected_dataset_ids : typing.Optional[typing.Sequence[str]]
            Optional list of watchlist dataset IDs connected to this job.

        fetch_all_watchlist_news : typing.Optional[bool]
            When true, returns generic news validators and enrichments suitable for
            watchlist-based article collection instead of query-specific fields.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[InitializeResponseDto]
            Suggestions retrieved successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "catchAll/initialize",
            method="POST",
            json={
                "query": query,
                "context": context,
                "connected_dataset_ids": connected_dataset_ids,
                "fetch_all_watchlist_news": fetch_all_watchlist_news,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    InitializeResponseDto,
                    parse_obj_as(
                        type_=InitializeResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_job(
        self,
        *,
        query: Query,
        context: typing.Optional[Context] = OMIT,
        limit: typing.Optional[Limit] = OMIT,
        start_date: typing.Optional[StartDate] = OMIT,
        end_date: typing.Optional[EndDate] = OMIT,
        validators: typing.Optional[typing.Sequence[ValidatorSchema]] = OMIT,
        enrichments: typing.Optional[typing.Sequence[EnrichmentSchema]] = OMIT,
        mode: typing.Optional[SubmitRequestDtoMode] = OMIT,
        connected_dataset_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        ed_score_min: typing.Optional[int] = OMIT,
        project_id: typing.Optional[str] = OMIT,
        webhook_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        fetch_all_watchlist_news: typing.Optional[bool] = OMIT,
        ed_association_type: typing.Optional[EntityAssociationType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SubmitResponseDto]:
        """
        Submit a query to create a new processing job.

        Parameters
        ----------
        query : Query

        context : typing.Optional[Context]

        limit : typing.Optional[Limit]

        start_date : typing.Optional[StartDate]

        end_date : typing.Optional[EndDate]

        validators : typing.Optional[typing.Sequence[ValidatorSchema]]
            Custom validators for filtering web page clusters.

            If not provided, validators are generated automatically based on the query.

        enrichments : typing.Optional[typing.Sequence[EnrichmentSchema]]
            Custom enrichment fields for data extraction.

            If not provided, enrichments are generated automatically based on the query.

        mode : typing.Optional[SubmitRequestDtoMode]
            Job processing mode.

            - `base`: Full pipeline with validation and enrichment.
            - `lite`: Lightweight extraction with faster processing. Returns titles and citations only.

        connected_dataset_ids : typing.Optional[typing.Sequence[str]]
            Dataset IDs to connect to the job. When provided, this enables Company Watchlist mode — the job returns only events relevant to companies in the connected datasets. To set the minimum relevance threshold, use `ed_score_min`.

            The dataset must have `latest_status: ready` before the job is submitted. Submitting with a non-existent or inaccessible dataset ID returns `400`.

        ed_score_min : typing.Optional[int]
            The minimum relevance score a connected entity must reach for its record to be included in results.

            Only valid when `connected_dataset_ids` is set; otherwise ignored. Records where no connected entity meets the threshold are excluded entirely.

        project_id : typing.Optional[str]
            Project to assign this job to. The job appears in the project's resource list immediately after submission.

        webhook_ids : typing.Optional[typing.Sequence[str]]
            IDs of webhooks to notify when the job completes. Maximum 5 per job.

        fetch_all_watchlist_news : typing.Optional[bool]
            When true, retrieves all news for connected Company Watchlist entities
            without topic filtering. Requires connected_dataset_ids to be set.

        ed_association_type : typing.Optional[EntityAssociationType]
            Filter events by entity association type. `event_associated` keeps only
            events where the entity is a direct actor. `mention` keeps only events
            where the entity is merely referenced. Only relevant when
            connected_dataset_ids is set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SubmitResponseDto]
            Job created successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "catchAll/submit",
            method="POST",
            json={
                "query": query,
                "context": context,
                "limit": limit,
                "start_date": start_date,
                "end_date": end_date,
                "validators": convert_and_respect_annotation_metadata(
                    object_=validators, annotation=typing.Sequence[ValidatorSchema], direction="write"
                ),
                "enrichments": convert_and_respect_annotation_metadata(
                    object_=enrichments, annotation=typing.Sequence[EnrichmentSchema], direction="write"
                ),
                "mode": mode,
                "connected_dataset_ids": connected_dataset_ids,
                "ed_score_min": ed_score_min,
                "project_id": project_id,
                "webhook_ids": webhook_ids,
                "fetch_all_watchlist_news": fetch_all_watchlist_news,
                "ed_association_type": ed_association_type,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubmitResponseDto,
                    parse_obj_as(
                        type_=SubmitResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_job_status(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[StatusResponseDto]:
        """
        Retrieve the current processing status of a job.

        Parameters
        ----------
        job_id : str
            Unique job identifier returned from [`POST /catchAll/submit`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/jobs/create-job).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[StatusResponseDto]
            Status retrieved successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/status/{encode_path_param(job_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    StatusResponseDto,
                    parse_obj_as(
                        type_=StatusResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_job_results(
        self,
        job_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PullJobResponseDto]:
        """
        Retrieve the final results for a completed job.

        Parameters
        ----------
        job_id : str
            Unique job identifier returned from [`POST /catchAll/submit`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/jobs/create-job).

        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of records per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PullJobResponseDto]
            Results retrieved successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/pull/{encode_path_param(job_id)}",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PullJobResponseDto,
                    parse_obj_as(
                        type_=PullJobResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def continue_job(
        self,
        *,
        job_id: str,
        new_limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ContinueResponseDto]:
        """
        Continue an existing job to process more records beyond the initial limit.

        Parameters
        ----------
        job_id : str
            Job identifier of the completed job to continue.

        new_limit : typing.Optional[int]
            New record limit for continued processing. Must be greater than the previous limit. If not provided, defaults to the plan maximum.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ContinueResponseDto]
            Job continuation accepted
        """
        _response = await self._client_wrapper.httpx_client.request(
            "catchAll/continue",
            method="POST",
            json={
                "job_id": job_id,
                "new_limit": new_limit,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ContinueResponseDto,
                    parse_obj_as(
                        type_=ContinueResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        parse_obj_as(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_job(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DeleteJobResponseDto]:
        """
        Soft-deletes a job. The job is flagged as deleted and no longer appears in list results. The underlying data is retained.

        Only the job owner can delete a job. Returns `404` if the job is not found or does not belong to the authenticated user.

        Deleting an already-deleted job returns `200`.

        Parameters
        ----------
        job_id : str
            Unique job identifier returned from [`POST /catchAll/submit`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/jobs/create-job).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeleteJobResponseDto]
            Job deleted successfully (or already deleted).
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"catchAll/jobs/{encode_path_param(job_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeleteJobResponseDto,
                    parse_obj_as(
                        type_=DeleteJobResponseDto,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
