# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.assign_webhook_resource_response_dto import AssignWebhookResourceResponseDto
from ..types.create_webhook_response_dto import CreateWebhookResponseDto
from ..types.delivery_history_response_dto import DeliveryHistoryResponseDto
from ..types.delivery_mode import DeliveryMode
from ..types.formatter_config_dto import FormatterConfigDto
from ..types.get_webhook_response_dto import GetWebhookResponseDto
from ..types.http_method import HttpMethod
from ..types.list_webhook_resources_response_dto import ListWebhookResourcesResponseDto
from ..types.list_webhooks_response_dto import ListWebhooksResponseDto
from ..types.mappable_resource_type import MappableResourceType
from ..types.test_webhook_response_dto import TestWebhookResponseDto
from ..types.update_webhook_response_dto import UpdateWebhookResponseDto
from ..types.webhook_type import WebhookType
from .raw_client import AsyncRawWebhooksClient, RawWebhooksClient
from .types.create_webhook_request_dto_auth import CreateWebhookRequestDtoAuth
from .types.update_webhook_request_dto_auth import UpdateWebhookRequestDtoAuth

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebhooksClient
        """
        return self._raw_client

    def list_webhooks(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWebhooksResponseDto:
        """
        Returns a paginated list of webhooks belonging to the organization.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of webhooks per page.

        search : typing.Optional[str]
            Filter results by text (case-insensitive substring match).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponseDto
            Webhooks retrieved successfully.

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.list_webhooks()
        """
        _response = self._raw_client.list_webhooks(
            page=page, page_size=page_size, search=search, request_options=request_options
        )
        return _response.data

    def create_webhook(
        self,
        *,
        name: str,
        url: str,
        type: typing.Optional[WebhookType] = OMIT,
        delivery_mode: typing.Optional[DeliveryMode] = OMIT,
        method: typing.Optional[HttpMethod] = OMIT,
        headers: typing.Optional[typing.Dict[str, str]] = OMIT,
        params: typing.Optional[typing.Dict[str, str]] = OMIT,
        auth: typing.Optional[CreateWebhookRequestDtoAuth] = OMIT,
        formatter_config: typing.Optional[FormatterConfigDto] = OMIT,
        project_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateWebhookResponseDto:
        """
        Creates a new webhook endpoint for the organization.

        Optionally pass `project_id` to attach the webhook to a project in the same request.

        Parameters
        ----------
        name : str
            Human-readable label for this webhook.

        url : str
            Destination URL that receives the payload. Must use HTTPS. IP addresses are not accepted.

            Type-specific URL requirements:
            - `slack`: Must start with `https://hooks.slack.com/`.
            - `teams`: Hostname must match `*.webhook.office.com` or `*.webhook.office365.com`.
            - `generic`: Any valid HTTPS domain.
            - `custom`: Any valid HTTPS domain.

            When `type` is omitted, it is auto-detected from the URL.

        type : typing.Optional[WebhookType]

        delivery_mode : typing.Optional[DeliveryMode]

        method : typing.Optional[HttpMethod]

        headers : typing.Optional[typing.Dict[str, str]]
            Custom HTTP headers forwarded with each delivery.

        params : typing.Optional[typing.Dict[str, str]]
            Query parameters appended to the webhook URL.

        auth : typing.Optional[CreateWebhookRequestDtoAuth]
            Authentication forwarded with each delivery. Supported types:
            - `bearer`: Adds an `Authorization: Bearer <token>` header.
            - `api_key`: Adds a custom header with the specified name and value.
            - `basic`: Adds an `Authorization: Basic <credentials>` header.

        formatter_config : typing.Optional[FormatterConfigDto]
            Custom payload formatter. Required when `type` is `custom`.

        project_id : typing.Optional[str]
            Optional project to attach this webhook to at creation time. Equivalent
            to creating the webhook and then calling
            [`POST /catchAll/projects/{project_id}/resources`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/projects/add-resource)
            with `resource_type: webhook`.

            The project must belong to your organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateWebhookResponseDto
            Webhook created successfully.

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.create_webhook(
            name="Layoffs Alert",
            url="https://hooks.slack.com/services/T000/B000/xxx",
            type="slack",
            delivery_mode="full",
            project_id="60a85db4-78ec-4b78-876a-bc7d9cdadd04",
        )
        """
        _response = self._raw_client.create_webhook(
            name=name,
            url=url,
            type=type,
            delivery_mode=delivery_mode,
            method=method,
            headers=headers,
            params=params,
            auth=auth,
            formatter_config=formatter_config,
            project_id=project_id,
            request_options=request_options,
        )
        return _response.data

    def get_webhook(
        self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetWebhookResponseDto:
        """
        Returns the full configuration of a single webhook by ID.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebhookResponseDto
            Webhook retrieved successfully.

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.get_webhook(
            webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        )
        """
        _response = self._raw_client.get_webhook(webhook_id, request_options=request_options)
        return _response.data

    def delete_webhook(self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes a webhook and removes all resource assignments.

        Assigned jobs and monitors no longer trigger delivery to this webhook. This operation cannot be undone.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.delete_webhook(
            webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        )
        """
        _response = self._raw_client.delete_webhook(webhook_id, request_options=request_options)
        return _response.data

    def update_webhook(
        self,
        webhook_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        url: typing.Optional[str] = OMIT,
        type: typing.Optional[WebhookType] = OMIT,
        delivery_mode: typing.Optional[DeliveryMode] = OMIT,
        method: typing.Optional[HttpMethod] = OMIT,
        headers: typing.Optional[typing.Dict[str, str]] = OMIT,
        params: typing.Optional[typing.Dict[str, str]] = OMIT,
        auth: typing.Optional[UpdateWebhookRequestDtoAuth] = OMIT,
        formatter_config: typing.Optional[FormatterConfigDto] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateWebhookResponseDto:
        """
        Updates one or more fields of an existing webhook.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        name : typing.Optional[str]
            Updated webhook name.

        url : typing.Optional[str]
            Updated destination URL. Must use HTTPS. Type-specific URL rules apply.

        type : typing.Optional[WebhookType]

        delivery_mode : typing.Optional[DeliveryMode]

        method : typing.Optional[HttpMethod]

        headers : typing.Optional[typing.Dict[str, str]]
            Updated HTTP headers. Replaces existing headers entirely.

        params : typing.Optional[typing.Dict[str, str]]
            Updated query parameters. Replaces existing params entirely.

        auth : typing.Optional[UpdateWebhookRequestDtoAuth]
            Updated authentication configuration. Replaces existing auth entirely.

        formatter_config : typing.Optional[FormatterConfigDto]
            Updated custom payload formatter. Set only when `type` is `custom`.

        is_active : typing.Optional[bool]
            Set to `false` to disable delivery without deleting the webhook.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateWebhookResponseDto
            Webhook updated successfully.

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.update_webhook(
            webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            name="Layoffs Alert (EU)",
            is_active=False,
        )
        """
        _response = self._raw_client.update_webhook(
            webhook_id,
            name=name,
            url=url,
            type=type,
            delivery_mode=delivery_mode,
            method=method,
            headers=headers,
            params=params,
            auth=auth,
            formatter_config=formatter_config,
            is_active=is_active,
            request_options=request_options,
        )
        return _response.data

    def test_webhook(
        self,
        webhook_id: str,
        *,
        payload: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TestWebhookResponseDto:
        """
        Sends a test HTTP request to the webhook URL using the webhook's configured method, headers, and auth. Returns the response from the target endpoint.

        Use this to verify URL reachability and authentication before attaching the webhook to a live job or monitor.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        payload : typing.Optional[typing.Dict[str, typing.Any]]
            Custom payload to send in the test request. If omitted, a synthetic
            test payload is sent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestWebhookResponseDto
            Test delivery attempted. Check `success` and `http_status_code` for the outcome.

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.test_webhook(
            webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            payload={"test": True, "message": "CatchAll webhook test"},
        )
        """
        _response = self._raw_client.test_webhook(webhook_id, payload=payload, request_options=request_options)
        return _response.data

    def list_webhook_resources(
        self,
        webhook_id: str,
        *,
        resource_type: typing.Optional[MappableResourceType] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWebhookResourcesResponseDto:
        """
        Returns a paginated list of resources currently assigned to this webhook.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        resource_type : typing.Optional[MappableResourceType]

        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of assignments per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhookResourcesResponseDto
            Webhook resource assignments retrieved successfully.

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.list_webhook_resources(
            webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        )
        """
        _response = self._raw_client.list_webhook_resources(
            webhook_id, resource_type=resource_type, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def assign_webhook_resource(
        self,
        webhook_id: str,
        *,
        resource_type: MappableResourceType,
        resource_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AssignWebhookResourceResponseDto:
        """
        Attaches a job, monitor, or monitor group to the webhook. When the
        resource completes, the webhook receives a delivery.

        A single webhook can be assigned to multiple resources. Each resource
        can have up to 5 webhooks assigned.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        resource_type : MappableResourceType
            Type of resource to assign.

        resource_id : str
            ID of the resource to assign.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AssignWebhookResourceResponseDto
            Resource assigned to webhook.

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.assign_webhook_resource(
            webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            resource_type="monitor",
            resource_id="3fec5b07-8786-46d7-9486-d43ff67eccd4",
        )
        """
        _response = self._raw_client.assign_webhook_resource(
            webhook_id, resource_type=resource_type, resource_id=resource_id, request_options=request_options
        )
        return _response.data

    def remove_webhook_resource(
        self,
        webhook_id: str,
        resource_type: MappableResourceType,
        resource_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Detaches a resource from this webhook. Completions of the resource no longer trigger delivery to this webhook.

        The webhook and the resource itself are not deleted.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        resource_type : MappableResourceType

        resource_id : str
            Unique resource identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.remove_webhook_resource(
            webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            resource_type="job",
            resource_id="3fec5b07-8786-46d7-9486-d43ff67eccd4",
        )
        """
        _response = self._raw_client.remove_webhook_resource(
            webhook_id, resource_type, resource_id, request_options=request_options
        )
        return _response.data

    def list_webhooks_for_resource(
        self,
        resource_type: MappableResourceType,
        resource_id: str,
        *,
        is_active: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWebhooksResponseDto:
        """
        Returns all webhooks currently assigned to the given resource.

        Parameters
        ----------
        resource_type : MappableResourceType

        resource_id : str
            Unique resource identifier.

        is_active : typing.Optional[bool]
            Filter by active status. Omit to return webhooks regardless of status.

        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of webhooks per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponseDto
            Webhooks for resource retrieved successfully.

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.list_webhooks_for_resource(
            resource_type="job",
            resource_id="3fec5b07-8786-46d7-9486-d43ff67eccd4",
        )
        """
        _response = self._raw_client.list_webhooks_for_resource(
            resource_type,
            resource_id,
            is_active=is_active,
            page=page,
            page_size=page_size,
            request_options=request_options,
        )
        return _response.data

    def trigger_webhook(
        self,
        resource_type: MappableResourceType,
        resource_id: str,
        *,
        webhook_id: str,
        job_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Manually dispatches a webhook delivery for a resource on demand, without
        waiting for the next job or monitor cycle.

        Use this to re-deliver results after a failed delivery, replay a specific
        job's results, or validate a webhook against live data. The webhook must
        already be assigned to the resource.

        Parameters
        ----------
        resource_type : MappableResourceType

        resource_id : str
            Unique resource identifier.

        webhook_id : str
            Identifier of the webhook to trigger. Must be assigned to the resource.

        job_id : typing.Optional[str]
            Specific job run to deliver. Optional for `job` resources; for
            `monitor` and `monitor_group` resources, selects a past run to replay.
            When omitted, the latest available results are delivered.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.trigger_webhook(
            resource_type="job",
            resource_id="3fec5b07-8786-46d7-9486-d43ff67eccd4",
            webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            job_id="3fec5b07-8786-46d7-9486-d43ff67eccd4",
        )
        """
        _response = self._raw_client.trigger_webhook(
            resource_type, resource_id, webhook_id=webhook_id, job_id=job_id, request_options=request_options
        )
        return _response.data

    def get_webhook_delivery_history(
        self,
        *,
        resource_type: MappableResourceType,
        resource_id: str,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeliveryHistoryResponseDto:
        """
        Returns a paginated delivery log for a given resource, ordered by timestamp descending.

        Each record shows the webhook dispatched, the HTTP status code returned, delivery outcome, and any error or warning messages. Use this to debug failed deliveries or audit dispatch activity.

        Parameters
        ----------
        resource_type : MappableResourceType
            Type of the resource to retrieve delivery history for.

        resource_id : str
            Identifier of the resource to retrieve delivery history for.

        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of records per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeliveryHistoryResponseDto
            Webhook delivery history retrieved successfully.

        Examples
        --------
        from newscatcher_catchall import CatchAllApi

        client = CatchAllApi(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.get_webhook_delivery_history(
            resource_type="job",
            resource_id="3fec5b07-8786-46d7-9486-d43ff67eccd4",
        )
        """
        _response = self._raw_client.get_webhook_delivery_history(
            resource_type=resource_type,
            resource_id=resource_id,
            page=page,
            page_size=page_size,
            request_options=request_options,
        )
        return _response.data


class AsyncWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebhooksClient
        """
        return self._raw_client

    async def list_webhooks(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWebhooksResponseDto:
        """
        Returns a paginated list of webhooks belonging to the organization.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of webhooks per page.

        search : typing.Optional[str]
            Filter results by text (case-insensitive substring match).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponseDto
            Webhooks retrieved successfully.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.list_webhooks()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_webhooks(
            page=page, page_size=page_size, search=search, request_options=request_options
        )
        return _response.data

    async def create_webhook(
        self,
        *,
        name: str,
        url: str,
        type: typing.Optional[WebhookType] = OMIT,
        delivery_mode: typing.Optional[DeliveryMode] = OMIT,
        method: typing.Optional[HttpMethod] = OMIT,
        headers: typing.Optional[typing.Dict[str, str]] = OMIT,
        params: typing.Optional[typing.Dict[str, str]] = OMIT,
        auth: typing.Optional[CreateWebhookRequestDtoAuth] = OMIT,
        formatter_config: typing.Optional[FormatterConfigDto] = OMIT,
        project_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateWebhookResponseDto:
        """
        Creates a new webhook endpoint for the organization.

        Optionally pass `project_id` to attach the webhook to a project in the same request.

        Parameters
        ----------
        name : str
            Human-readable label for this webhook.

        url : str
            Destination URL that receives the payload. Must use HTTPS. IP addresses are not accepted.

            Type-specific URL requirements:
            - `slack`: Must start with `https://hooks.slack.com/`.
            - `teams`: Hostname must match `*.webhook.office.com` or `*.webhook.office365.com`.
            - `generic`: Any valid HTTPS domain.
            - `custom`: Any valid HTTPS domain.

            When `type` is omitted, it is auto-detected from the URL.

        type : typing.Optional[WebhookType]

        delivery_mode : typing.Optional[DeliveryMode]

        method : typing.Optional[HttpMethod]

        headers : typing.Optional[typing.Dict[str, str]]
            Custom HTTP headers forwarded with each delivery.

        params : typing.Optional[typing.Dict[str, str]]
            Query parameters appended to the webhook URL.

        auth : typing.Optional[CreateWebhookRequestDtoAuth]
            Authentication forwarded with each delivery. Supported types:
            - `bearer`: Adds an `Authorization: Bearer <token>` header.
            - `api_key`: Adds a custom header with the specified name and value.
            - `basic`: Adds an `Authorization: Basic <credentials>` header.

        formatter_config : typing.Optional[FormatterConfigDto]
            Custom payload formatter. Required when `type` is `custom`.

        project_id : typing.Optional[str]
            Optional project to attach this webhook to at creation time. Equivalent
            to creating the webhook and then calling
            [`POST /catchAll/projects/{project_id}/resources`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/projects/add-resource)
            with `resource_type: webhook`.

            The project must belong to your organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateWebhookResponseDto
            Webhook created successfully.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.create_webhook(
                name="Layoffs Alert",
                url="https://hooks.slack.com/services/T000/B000/xxx",
                type="slack",
                delivery_mode="full",
                project_id="60a85db4-78ec-4b78-876a-bc7d9cdadd04",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_webhook(
            name=name,
            url=url,
            type=type,
            delivery_mode=delivery_mode,
            method=method,
            headers=headers,
            params=params,
            auth=auth,
            formatter_config=formatter_config,
            project_id=project_id,
            request_options=request_options,
        )
        return _response.data

    async def get_webhook(
        self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetWebhookResponseDto:
        """
        Returns the full configuration of a single webhook by ID.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetWebhookResponseDto
            Webhook retrieved successfully.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.get_webhook(
                webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_webhook(webhook_id, request_options=request_options)
        return _response.data

    async def delete_webhook(self, webhook_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes a webhook and removes all resource assignments.

        Assigned jobs and monitors no longer trigger delivery to this webhook. This operation cannot be undone.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.delete_webhook(
                webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_webhook(webhook_id, request_options=request_options)
        return _response.data

    async def update_webhook(
        self,
        webhook_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        url: typing.Optional[str] = OMIT,
        type: typing.Optional[WebhookType] = OMIT,
        delivery_mode: typing.Optional[DeliveryMode] = OMIT,
        method: typing.Optional[HttpMethod] = OMIT,
        headers: typing.Optional[typing.Dict[str, str]] = OMIT,
        params: typing.Optional[typing.Dict[str, str]] = OMIT,
        auth: typing.Optional[UpdateWebhookRequestDtoAuth] = OMIT,
        formatter_config: typing.Optional[FormatterConfigDto] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateWebhookResponseDto:
        """
        Updates one or more fields of an existing webhook.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        name : typing.Optional[str]
            Updated webhook name.

        url : typing.Optional[str]
            Updated destination URL. Must use HTTPS. Type-specific URL rules apply.

        type : typing.Optional[WebhookType]

        delivery_mode : typing.Optional[DeliveryMode]

        method : typing.Optional[HttpMethod]

        headers : typing.Optional[typing.Dict[str, str]]
            Updated HTTP headers. Replaces existing headers entirely.

        params : typing.Optional[typing.Dict[str, str]]
            Updated query parameters. Replaces existing params entirely.

        auth : typing.Optional[UpdateWebhookRequestDtoAuth]
            Updated authentication configuration. Replaces existing auth entirely.

        formatter_config : typing.Optional[FormatterConfigDto]
            Updated custom payload formatter. Set only when `type` is `custom`.

        is_active : typing.Optional[bool]
            Set to `false` to disable delivery without deleting the webhook.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateWebhookResponseDto
            Webhook updated successfully.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.update_webhook(
                webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                name="Layoffs Alert (EU)",
                is_active=False,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_webhook(
            webhook_id,
            name=name,
            url=url,
            type=type,
            delivery_mode=delivery_mode,
            method=method,
            headers=headers,
            params=params,
            auth=auth,
            formatter_config=formatter_config,
            is_active=is_active,
            request_options=request_options,
        )
        return _response.data

    async def test_webhook(
        self,
        webhook_id: str,
        *,
        payload: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TestWebhookResponseDto:
        """
        Sends a test HTTP request to the webhook URL using the webhook's configured method, headers, and auth. Returns the response from the target endpoint.

        Use this to verify URL reachability and authentication before attaching the webhook to a live job or monitor.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        payload : typing.Optional[typing.Dict[str, typing.Any]]
            Custom payload to send in the test request. If omitted, a synthetic
            test payload is sent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestWebhookResponseDto
            Test delivery attempted. Check `success` and `http_status_code` for the outcome.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.test_webhook(
                webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                payload={"test": True, "message": "CatchAll webhook test"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.test_webhook(webhook_id, payload=payload, request_options=request_options)
        return _response.data

    async def list_webhook_resources(
        self,
        webhook_id: str,
        *,
        resource_type: typing.Optional[MappableResourceType] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWebhookResourcesResponseDto:
        """
        Returns a paginated list of resources currently assigned to this webhook.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        resource_type : typing.Optional[MappableResourceType]

        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of assignments per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhookResourcesResponseDto
            Webhook resource assignments retrieved successfully.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.list_webhook_resources(
                webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_webhook_resources(
            webhook_id, resource_type=resource_type, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def assign_webhook_resource(
        self,
        webhook_id: str,
        *,
        resource_type: MappableResourceType,
        resource_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AssignWebhookResourceResponseDto:
        """
        Attaches a job, monitor, or monitor group to the webhook. When the
        resource completes, the webhook receives a delivery.

        A single webhook can be assigned to multiple resources. Each resource
        can have up to 5 webhooks assigned.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        resource_type : MappableResourceType
            Type of resource to assign.

        resource_id : str
            ID of the resource to assign.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AssignWebhookResourceResponseDto
            Resource assigned to webhook.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.assign_webhook_resource(
                webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                resource_type="monitor",
                resource_id="3fec5b07-8786-46d7-9486-d43ff67eccd4",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.assign_webhook_resource(
            webhook_id, resource_type=resource_type, resource_id=resource_id, request_options=request_options
        )
        return _response.data

    async def remove_webhook_resource(
        self,
        webhook_id: str,
        resource_type: MappableResourceType,
        resource_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Detaches a resource from this webhook. Completions of the resource no longer trigger delivery to this webhook.

        The webhook and the resource itself are not deleted.

        Parameters
        ----------
        webhook_id : str
            Unique webhook identifier.

        resource_type : MappableResourceType

        resource_id : str
            Unique resource identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.remove_webhook_resource(
                webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                resource_type="job",
                resource_id="3fec5b07-8786-46d7-9486-d43ff67eccd4",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_webhook_resource(
            webhook_id, resource_type, resource_id, request_options=request_options
        )
        return _response.data

    async def list_webhooks_for_resource(
        self,
        resource_type: MappableResourceType,
        resource_id: str,
        *,
        is_active: typing.Optional[bool] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWebhooksResponseDto:
        """
        Returns all webhooks currently assigned to the given resource.

        Parameters
        ----------
        resource_type : MappableResourceType

        resource_id : str
            Unique resource identifier.

        is_active : typing.Optional[bool]
            Filter by active status. Omit to return webhooks regardless of status.

        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of webhooks per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponseDto
            Webhooks for resource retrieved successfully.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.list_webhooks_for_resource(
                resource_type="job",
                resource_id="3fec5b07-8786-46d7-9486-d43ff67eccd4",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_webhooks_for_resource(
            resource_type,
            resource_id,
            is_active=is_active,
            page=page,
            page_size=page_size,
            request_options=request_options,
        )
        return _response.data

    async def trigger_webhook(
        self,
        resource_type: MappableResourceType,
        resource_id: str,
        *,
        webhook_id: str,
        job_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Manually dispatches a webhook delivery for a resource on demand, without
        waiting for the next job or monitor cycle.

        Use this to re-deliver results after a failed delivery, replay a specific
        job's results, or validate a webhook against live data. The webhook must
        already be assigned to the resource.

        Parameters
        ----------
        resource_type : MappableResourceType

        resource_id : str
            Unique resource identifier.

        webhook_id : str
            Identifier of the webhook to trigger. Must be assigned to the resource.

        job_id : typing.Optional[str]
            Specific job run to deliver. Optional for `job` resources; for
            `monitor` and `monitor_group` resources, selects a past run to replay.
            When omitted, the latest available results are delivered.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.trigger_webhook(
                resource_type="job",
                resource_id="3fec5b07-8786-46d7-9486-d43ff67eccd4",
                webhook_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                job_id="3fec5b07-8786-46d7-9486-d43ff67eccd4",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.trigger_webhook(
            resource_type, resource_id, webhook_id=webhook_id, job_id=job_id, request_options=request_options
        )
        return _response.data

    async def get_webhook_delivery_history(
        self,
        *,
        resource_type: MappableResourceType,
        resource_id: str,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeliveryHistoryResponseDto:
        """
        Returns a paginated delivery log for a given resource, ordered by timestamp descending.

        Each record shows the webhook dispatched, the HTTP status code returned, delivery outcome, and any error or warning messages. Use this to debug failed deliveries or audit dispatch activity.

        Parameters
        ----------
        resource_type : MappableResourceType
            Type of the resource to retrieve delivery history for.

        resource_id : str
            Identifier of the resource to retrieve delivery history for.

        page : typing.Optional[int]
            Page number to retrieve.

        page_size : typing.Optional[int]
            Number of records per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeliveryHistoryResponseDto
            Webhook delivery history retrieved successfully.

        Examples
        --------
        import asyncio

        from newscatcher_catchall import AsyncCatchAllApi

        client = AsyncCatchAllApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.get_webhook_delivery_history(
                resource_type="job",
                resource_id="3fec5b07-8786-46d7-9486-d43ff67eccd4",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_webhook_delivery_history(
            resource_type=resource_type,
            resource_id=resource_id,
            page=page,
            page_size=page_size,
            request_options=request_options,
        )
        return _response.data
